/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateAlertRuleRequest,
    CreateAlertRuleRequestFromJSON,
    CreateAlertRuleRequestToJSON,
} from '../models/CreateAlertRuleRequest';
import {
    type DataEnvelope,
    DataEnvelopeFromJSON,
    DataEnvelopeToJSON,
} from '../models/DataEnvelope';
import {
    type ListEnvelope,
    ListEnvelopeFromJSON,
    ListEnvelopeToJSON,
} from '../models/ListEnvelope';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type UpdateAlertRuleRequest,
    UpdateAlertRuleRequestFromJSON,
    UpdateAlertRuleRequestToJSON,
} from '../models/UpdateAlertRuleRequest';
import {
    type UpdateAlertSettingsRequest,
    UpdateAlertSettingsRequestFromJSON,
    UpdateAlertSettingsRequestToJSON,
} from '../models/UpdateAlertSettingsRequest';

export interface CreateAlertRuleOperationRequest {
    idempotencyKey: string;
    createAlertRuleRequest: CreateAlertRuleRequest;
}

export interface DeleteAlertRuleRequest {
    idempotencyKey: string;
    alertRuleId: string;
}

export interface GetAlertRuleRequest {
    alertRuleId: string;
}

export interface ListAlertEventsRequest {
    page?: number;
    size?: number;
    search?: string;
    acknowledged?: boolean | null;
    historyDays?: number;
    eventType?: string;
}

export interface ListAlertRulesRequest {
    page?: number;
    size?: number;
    search?: string;
    isActive?: boolean | null;
    condition?: string;
}

export interface UpdateAlertRuleOperationRequest {
    idempotencyKey: string;
    alertRuleId: string;
    updateAlertRuleRequest: UpdateAlertRuleRequest;
}

export interface UpdateAlertSettingsOperationRequest {
    idempotencyKey: string;
    updateAlertSettingsRequest: UpdateAlertSettingsRequest;
}

/**
 * AlertsApi - interface
 * 
 * @export
 * @interface AlertsApiInterface
 */
export interface AlertsApiInterface {
    /**
     * Creates request options for createAlertRule without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateAlertRuleRequest} createAlertRuleRequest 
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    createAlertRuleRequestOpts(requestParameters: CreateAlertRuleOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create an alert rule
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateAlertRuleRequest} createAlertRuleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    createAlertRuleRaw(requestParameters: CreateAlertRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Create an alert rule
     */
    createAlertRule(requestParameters: CreateAlertRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for deleteAlertRule without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} alertRuleId 
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    deleteAlertRuleRequestOpts(requestParameters: DeleteAlertRuleRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Delete an alert rule
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} alertRuleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    deleteAlertRuleRaw(requestParameters: DeleteAlertRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Delete an alert rule
     */
    deleteAlertRule(requestParameters: DeleteAlertRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getAlertRule without sending the request
     * @param {string} alertRuleId 
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    getAlertRuleRequestOpts(requestParameters: GetAlertRuleRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get an alert rule
     * @param {string} alertRuleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    getAlertRuleRaw(requestParameters: GetAlertRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get an alert rule
     */
    getAlertRule(requestParameters: GetAlertRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getAlertSettings without sending the request
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    getAlertSettingsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get alert settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    getAlertSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get alert settings
     */
    getAlertSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for listAlertEvents without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {boolean} [acknowledged] 
     * @param {number} [historyDays] 
     * @param {string} [eventType] 
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    listAlertEventsRequestOpts(requestParameters: ListAlertEventsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List alert events
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {boolean} [acknowledged] 
     * @param {number} [historyDays] 
     * @param {string} [eventType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    listAlertEventsRaw(requestParameters: ListAlertEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List alert events
     */
    listAlertEvents(requestParameters: ListAlertEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for listAlertRules without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {boolean} [isActive] 
     * @param {string} [condition] 
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    listAlertRulesRequestOpts(requestParameters: ListAlertRulesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List alert rules
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {boolean} [isActive] 
     * @param {string} [condition] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    listAlertRulesRaw(requestParameters: ListAlertRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List alert rules
     */
    listAlertRules(requestParameters: ListAlertRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for updateAlertRule without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} alertRuleId 
     * @param {UpdateAlertRuleRequest} updateAlertRuleRequest 
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    updateAlertRuleRequestOpts(requestParameters: UpdateAlertRuleOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update an alert rule
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} alertRuleId 
     * @param {UpdateAlertRuleRequest} updateAlertRuleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    updateAlertRuleRaw(requestParameters: UpdateAlertRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Update an alert rule
     */
    updateAlertRule(requestParameters: UpdateAlertRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for updateAlertSettings without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {UpdateAlertSettingsRequest} updateAlertSettingsRequest 
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    updateAlertSettingsRequestOpts(requestParameters: UpdateAlertSettingsOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update alert settings
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {UpdateAlertSettingsRequest} updateAlertSettingsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlertsApiInterface
     */
    updateAlertSettingsRaw(requestParameters: UpdateAlertSettingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Update alert settings
     */
    updateAlertSettings(requestParameters: UpdateAlertSettingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

}

/**
 * 
 */
export class AlertsApi extends runtime.BaseAPI implements AlertsApiInterface {

    /**
     * Creates request options for createAlertRule without sending the request
     */
    async createAlertRuleRequestOpts(requestParameters: CreateAlertRuleOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createAlertRule().'
            );
        }

        if (requestParameters['createAlertRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'createAlertRuleRequest',
                'Required parameter "createAlertRuleRequest" was null or undefined when calling createAlertRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["alerts:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/alert-rules`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAlertRuleRequestToJSON(requestParameters['createAlertRuleRequest']),
        };
    }

    /**
     * Create an alert rule
     */
    async createAlertRuleRaw(requestParameters: CreateAlertRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.createAlertRuleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create an alert rule
     */
    async createAlertRule(requestParameters: CreateAlertRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.createAlertRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteAlertRule without sending the request
     */
    async deleteAlertRuleRequestOpts(requestParameters: DeleteAlertRuleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling deleteAlertRule().'
            );
        }

        if (requestParameters['alertRuleId'] == null) {
            throw new runtime.RequiredError(
                'alertRuleId',
                'Required parameter "alertRuleId" was null or undefined when calling deleteAlertRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["alerts:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/alert-rules/{alert_rule_id}`;
        urlPath = urlPath.replace('{alert_rule_id}', encodeURIComponent(String(requestParameters['alertRuleId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an alert rule
     */
    async deleteAlertRuleRaw(requestParameters: DeleteAlertRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.deleteAlertRuleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete an alert rule
     */
    async deleteAlertRule(requestParameters: DeleteAlertRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.deleteAlertRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAlertRule without sending the request
     */
    async getAlertRuleRequestOpts(requestParameters: GetAlertRuleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['alertRuleId'] == null) {
            throw new runtime.RequiredError(
                'alertRuleId',
                'Required parameter "alertRuleId" was null or undefined when calling getAlertRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["alerts:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/alert-rules/{alert_rule_id}`;
        urlPath = urlPath.replace('{alert_rule_id}', encodeURIComponent(String(requestParameters['alertRuleId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get an alert rule
     */
    async getAlertRuleRaw(requestParameters: GetAlertRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getAlertRuleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get an alert rule
     */
    async getAlertRule(requestParameters: GetAlertRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getAlertRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAlertSettings without sending the request
     */
    async getAlertSettingsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["alerts:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/alert-settings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get alert settings
     */
    async getAlertSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getAlertSettingsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get alert settings
     */
    async getAlertSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getAlertSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAlertEvents without sending the request
     */
    async listAlertEventsRequestOpts(requestParameters: ListAlertEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['acknowledged'] != null) {
            queryParameters['acknowledged'] = requestParameters['acknowledged'];
        }

        if (requestParameters['historyDays'] != null) {
            queryParameters['historyDays'] = requestParameters['historyDays'];
        }

        if (requestParameters['eventType'] != null) {
            queryParameters['eventType'] = requestParameters['eventType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["alerts:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/alert-events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List alert events
     */
    async listAlertEventsRaw(requestParameters: ListAlertEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listAlertEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List alert events
     */
    async listAlertEvents(requestParameters: ListAlertEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listAlertEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAlertRules without sending the request
     */
    async listAlertRulesRequestOpts(requestParameters: ListAlertRulesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['isActive'] != null) {
            queryParameters['isActive'] = requestParameters['isActive'];
        }

        if (requestParameters['condition'] != null) {
            queryParameters['condition'] = requestParameters['condition'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["alerts:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/alert-rules`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List alert rules
     */
    async listAlertRulesRaw(requestParameters: ListAlertRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listAlertRulesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List alert rules
     */
    async listAlertRules(requestParameters: ListAlertRulesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listAlertRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAlertRule without sending the request
     */
    async updateAlertRuleRequestOpts(requestParameters: UpdateAlertRuleOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateAlertRule().'
            );
        }

        if (requestParameters['alertRuleId'] == null) {
            throw new runtime.RequiredError(
                'alertRuleId',
                'Required parameter "alertRuleId" was null or undefined when calling updateAlertRule().'
            );
        }

        if (requestParameters['updateAlertRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAlertRuleRequest',
                'Required parameter "updateAlertRuleRequest" was null or undefined when calling updateAlertRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["alerts:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/alert-rules/{alert_rule_id}`;
        urlPath = urlPath.replace('{alert_rule_id}', encodeURIComponent(String(requestParameters['alertRuleId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAlertRuleRequestToJSON(requestParameters['updateAlertRuleRequest']),
        };
    }

    /**
     * Update an alert rule
     */
    async updateAlertRuleRaw(requestParameters: UpdateAlertRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.updateAlertRuleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Update an alert rule
     */
    async updateAlertRule(requestParameters: UpdateAlertRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.updateAlertRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAlertSettings without sending the request
     */
    async updateAlertSettingsRequestOpts(requestParameters: UpdateAlertSettingsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateAlertSettings().'
            );
        }

        if (requestParameters['updateAlertSettingsRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAlertSettingsRequest',
                'Required parameter "updateAlertSettingsRequest" was null or undefined when calling updateAlertSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["alerts:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/alert-settings`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAlertSettingsRequestToJSON(requestParameters['updateAlertSettingsRequest']),
        };
    }

    /**
     * Update alert settings
     */
    async updateAlertSettingsRaw(requestParameters: UpdateAlertSettingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.updateAlertSettingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Update alert settings
     */
    async updateAlertSettings(requestParameters: UpdateAlertSettingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.updateAlertSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
