/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DataEnvelope,
    DataEnvelopeFromJSON,
    DataEnvelopeToJSON,
} from '../models/DataEnvelope';
import {
    type ListEnvelope,
    ListEnvelopeFromJSON,
    ListEnvelopeToJSON,
} from '../models/ListEnvelope';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface GetProductRequest {
    productId: string;
}

export interface ListProductListingsRequest {
    productId: string;
}

export interface ListProductsRequest {
    page?: number;
    size?: number;
    search?: string;
    storeIds?: Array<string>;
    categoryIds?: Array<string>;
    brandIds?: Array<string>;
    changeType?: string;
    timeRange?: string;
    discounted?: boolean | null;
    includeOffers?: boolean | null;
    locale?: string;
}

/**
 * CatalogApi - interface
 * 
 * @export
 * @interface CatalogApiInterface
 */
export interface CatalogApiInterface {
    /**
     * Creates request options for getProduct without sending the request
     * @param {string} productId 
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    getProductRequestOpts(requestParameters: GetProductRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a published product
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get a published product
     */
    getProduct(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getProductFacets without sending the request
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    getProductFacetsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get product facets
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    getProductFacetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get product facets
     */
    getProductFacets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for listProductListings without sending the request
     * @param {string} productId 
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    listProductListingsRequestOpts(requestParameters: ListProductListingsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List product store offers
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    listProductListingsRaw(requestParameters: ListProductListingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * List product store offers
     */
    listProductListings(requestParameters: ListProductListingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for listProducts without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {Array<string>} [storeIds] 
     * @param {Array<string>} [categoryIds] 
     * @param {Array<string>} [brandIds] 
     * @param {string} [changeType] 
     * @param {string} [timeRange] 
     * @param {boolean} [discounted] 
     * @param {boolean} [includeOffers] 
     * @param {string} [locale] 
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    listProductsRequestOpts(requestParameters: ListProductsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List published products
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {Array<string>} [storeIds] 
     * @param {Array<string>} [categoryIds] 
     * @param {Array<string>} [brandIds] 
     * @param {string} [changeType] 
     * @param {string} [timeRange] 
     * @param {boolean} [discounted] 
     * @param {boolean} [includeOffers] 
     * @param {string} [locale] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List published products
     */
    listProducts(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

}

/**
 * 
 */
export class CatalogApi extends runtime.BaseAPI implements CatalogApiInterface {

    /**
     * Creates request options for getProduct without sending the request
     */
    async getProductRequestOpts(requestParameters: GetProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling getProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["catalog:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/products/{product_id}`;
        urlPath = urlPath.replace('{product_id}', encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a published product
     */
    async getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get a published product
     */
    async getProduct(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProductFacets without sending the request
     */
    async getProductFacetsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["catalog:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/products/facets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get product facets
     */
    async getProductFacetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getProductFacetsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get product facets
     */
    async getProductFacets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getProductFacetsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProductListings without sending the request
     */
    async listProductListingsRequestOpts(requestParameters: ListProductListingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling listProductListings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["catalog:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/products/{product_id}/listings`;
        urlPath = urlPath.replace('{product_id}', encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List product store offers
     */
    async listProductListingsRaw(requestParameters: ListProductListingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.listProductListingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * List product store offers
     */
    async listProductListings(requestParameters: ListProductListingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.listProductListingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProducts without sending the request
     */
    async listProductsRequestOpts(requestParameters: ListProductsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['storeIds'] != null) {
            queryParameters['storeIds'] = requestParameters['storeIds'];
        }

        if (requestParameters['categoryIds'] != null) {
            queryParameters['categoryIds'] = requestParameters['categoryIds'];
        }

        if (requestParameters['brandIds'] != null) {
            queryParameters['brandIds'] = requestParameters['brandIds'];
        }

        if (requestParameters['changeType'] != null) {
            queryParameters['changeType'] = requestParameters['changeType'];
        }

        if (requestParameters['timeRange'] != null) {
            queryParameters['timeRange'] = requestParameters['timeRange'];
        }

        if (requestParameters['discounted'] != null) {
            queryParameters['discounted'] = requestParameters['discounted'];
        }

        if (requestParameters['includeOffers'] != null) {
            queryParameters['includeOffers'] = requestParameters['includeOffers'];
        }

        if (requestParameters['locale'] != null) {
            queryParameters['locale'] = requestParameters['locale'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["catalog:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/products`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List published products
     */
    async listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List published products
     */
    async listProducts(requestParameters: ListProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
