/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CommercialProductLifecycleEnvelope,
    CommercialProductLifecycleEnvelopeFromJSON,
    CommercialProductLifecycleEnvelopeToJSON,
} from '../models/CommercialProductLifecycleEnvelope';
import {
    type CreateCommercialPartnerRequest,
    CreateCommercialPartnerRequestFromJSON,
    CreateCommercialPartnerRequestToJSON,
} from '../models/CreateCommercialPartnerRequest';
import {
    type CreateCommercialProductRequest,
    CreateCommercialProductRequestFromJSON,
    CreateCommercialProductRequestToJSON,
} from '../models/CreateCommercialProductRequest';
import {
    type DataEnvelope,
    DataEnvelopeFromJSON,
    DataEnvelopeToJSON,
} from '../models/DataEnvelope';
import {
    type DeleteCommercialProductRequest,
    DeleteCommercialProductRequestFromJSON,
    DeleteCommercialProductRequestToJSON,
} from '../models/DeleteCommercialProductRequest';
import {
    type ListEnvelope,
    ListEnvelopeFromJSON,
    ListEnvelopeToJSON,
} from '../models/ListEnvelope';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type SetMarketLinkRequest,
    SetMarketLinkRequestFromJSON,
    SetMarketLinkRequestToJSON,
} from '../models/SetMarketLinkRequest';
import {
    type UpdateCommercialPartnerRequest,
    UpdateCommercialPartnerRequestFromJSON,
    UpdateCommercialPartnerRequestToJSON,
} from '../models/UpdateCommercialPartnerRequest';
import {
    type UpdateCommercialProductRequest,
    UpdateCommercialProductRequestFromJSON,
    UpdateCommercialProductRequestToJSON,
} from '../models/UpdateCommercialProductRequest';

export interface ArchiveCommercialProductRequest {
    idempotencyKey: string;
    productId: string;
}

export interface CreateCommercialPartnerOperationRequest {
    idempotencyKey: string;
    createCommercialPartnerRequest: CreateCommercialPartnerRequest;
}

export interface CreateCommercialProductOperationRequest {
    idempotencyKey: string;
    createCommercialProductRequest: CreateCommercialProductRequest;
}

export interface DeleteCommercialProductOperationRequest {
    idempotencyKey: string;
    commercialProductId: string;
    deleteCommercialProductRequest: DeleteCommercialProductRequest;
}

export interface DeleteMarketLinkRequest {
    idempotencyKey: string;
    commercialProductId: string;
}

export interface GetCommercialPartnerRequest {
    partnerId: string;
}

export interface GetCommercialProductRequest {
    commercialProductId: string;
}

export interface GetMarketLinkRequest {
    commercialProductId: string;
}

export interface ListCommercialPartnersRequest {
    page?: number;
    size?: number;
    search?: string;
    role?: string;
    active?: boolean | null;
    sortBy?: string;
    sortDirection?: string;
}

export interface ListCommercialProductsRequest {
    page?: number;
    size?: number;
    search?: string;
    status?: string;
    matchState?: string;
    brands?: Array<string>;
    categories?: Array<string>;
    stockMin?: number | null;
    stockMax?: number | null;
    moneyField?: string;
    moneyMin?: number | null;
    moneyMax?: number | null;
    moneyCurrency?: string;
    smartFilters?: Array<string>;
    sortBy?: string;
    sortDirection?: string;
}

export interface RestoreCommercialProductRequest {
    idempotencyKey: string;
    productId: string;
}

export interface SetMarketLinkOperationRequest {
    idempotencyKey: string;
    commercialProductId: string;
    setMarketLinkRequest: SetMarketLinkRequest;
}

export interface UpdateCommercialPartnerOperationRequest {
    idempotencyKey: string;
    partnerId: string;
    updateCommercialPartnerRequest: UpdateCommercialPartnerRequest;
}

export interface UpdateCommercialProductOperationRequest {
    idempotencyKey: string;
    commercialProductId: string;
    updateCommercialProductRequest: UpdateCommercialProductRequest;
}

/**
 * CommercialCatalogApi - interface
 * 
 * @export
 * @interface CommercialCatalogApiInterface
 */
export interface CommercialCatalogApiInterface {
    /**
     * Creates request options for archiveCommercialProduct without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} productId 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    archiveCommercialProductRequestOpts(requestParameters: ArchiveCommercialProductRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Archive a commercial product
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    archiveCommercialProductRaw(requestParameters: ArchiveCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommercialProductLifecycleEnvelope>>;

    /**
     * Archive a commercial product
     */
    archiveCommercialProduct(requestParameters: ArchiveCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommercialProductLifecycleEnvelope>;

    /**
     * Creates request options for createCommercialPartner without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateCommercialPartnerRequest} createCommercialPartnerRequest 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    createCommercialPartnerRequestOpts(requestParameters: CreateCommercialPartnerOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a commercial partner
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateCommercialPartnerRequest} createCommercialPartnerRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    createCommercialPartnerRaw(requestParameters: CreateCommercialPartnerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Create a commercial partner
     */
    createCommercialPartner(requestParameters: CreateCommercialPartnerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for createCommercialProduct without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateCommercialProductRequest} createCommercialProductRequest 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    createCommercialProductRequestOpts(requestParameters: CreateCommercialProductOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a commercial product
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateCommercialProductRequest} createCommercialProductRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    createCommercialProductRaw(requestParameters: CreateCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Create a commercial product
     */
    createCommercialProduct(requestParameters: CreateCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for deleteCommercialProduct without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} commercialProductId 
     * @param {DeleteCommercialProductRequest} deleteCommercialProductRequest 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    deleteCommercialProductRequestOpts(requestParameters: DeleteCommercialProductOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Delete a commercial product
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} commercialProductId 
     * @param {DeleteCommercialProductRequest} deleteCommercialProductRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    deleteCommercialProductRaw(requestParameters: DeleteCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Delete a commercial product
     */
    deleteCommercialProduct(requestParameters: DeleteCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for deleteMarketLink without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} commercialProductId 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    deleteMarketLinkRequestOpts(requestParameters: DeleteMarketLinkRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Remove a market link
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} commercialProductId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    deleteMarketLinkRaw(requestParameters: DeleteMarketLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Remove a market link
     */
    deleteMarketLink(requestParameters: DeleteMarketLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getCommercialPartner without sending the request
     * @param {string} partnerId 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    getCommercialPartnerRequestOpts(requestParameters: GetCommercialPartnerRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a commercial partner
     * @param {string} partnerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    getCommercialPartnerRaw(requestParameters: GetCommercialPartnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get a commercial partner
     */
    getCommercialPartner(requestParameters: GetCommercialPartnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getCommercialProduct without sending the request
     * @param {string} commercialProductId 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    getCommercialProductRequestOpts(requestParameters: GetCommercialProductRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a commercial product
     * @param {string} commercialProductId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    getCommercialProductRaw(requestParameters: GetCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get a commercial product
     */
    getCommercialProduct(requestParameters: GetCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getMarketLink without sending the request
     * @param {string} commercialProductId 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    getMarketLinkRequestOpts(requestParameters: GetMarketLinkRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a market link
     * @param {string} commercialProductId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    getMarketLinkRaw(requestParameters: GetMarketLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get a market link
     */
    getMarketLink(requestParameters: GetMarketLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for listCommercialPartners without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {string} [role] 
     * @param {boolean} [active] 
     * @param {string} [sortBy] 
     * @param {string} [sortDirection] 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    listCommercialPartnersRequestOpts(requestParameters: ListCommercialPartnersRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List commercial partners
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {string} [role] 
     * @param {boolean} [active] 
     * @param {string} [sortBy] 
     * @param {string} [sortDirection] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    listCommercialPartnersRaw(requestParameters: ListCommercialPartnersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List commercial partners
     */
    listCommercialPartners(requestParameters: ListCommercialPartnersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for listCommercialProducts without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {string} [status] 
     * @param {string} [matchState] 
     * @param {Array<string>} [brands] 
     * @param {Array<string>} [categories] 
     * @param {number} [stockMin] 
     * @param {number} [stockMax] 
     * @param {string} [moneyField] 
     * @param {number} [moneyMin] 
     * @param {number} [moneyMax] 
     * @param {string} [moneyCurrency] 
     * @param {Array<string>} [smartFilters] 
     * @param {string} [sortBy] 
     * @param {string} [sortDirection] 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    listCommercialProductsRequestOpts(requestParameters: ListCommercialProductsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List commercial products
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {string} [status] 
     * @param {string} [matchState] 
     * @param {Array<string>} [brands] 
     * @param {Array<string>} [categories] 
     * @param {number} [stockMin] 
     * @param {number} [stockMax] 
     * @param {string} [moneyField] 
     * @param {number} [moneyMin] 
     * @param {number} [moneyMax] 
     * @param {string} [moneyCurrency] 
     * @param {Array<string>} [smartFilters] 
     * @param {string} [sortBy] 
     * @param {string} [sortDirection] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    listCommercialProductsRaw(requestParameters: ListCommercialProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List commercial products
     */
    listCommercialProducts(requestParameters: ListCommercialProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for restoreCommercialProduct without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} productId 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    restoreCommercialProductRequestOpts(requestParameters: RestoreCommercialProductRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Restore a commercial product
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    restoreCommercialProductRaw(requestParameters: RestoreCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommercialProductLifecycleEnvelope>>;

    /**
     * Restore a commercial product
     */
    restoreCommercialProduct(requestParameters: RestoreCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommercialProductLifecycleEnvelope>;

    /**
     * Creates request options for setMarketLink without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} commercialProductId 
     * @param {SetMarketLinkRequest} setMarketLinkRequest 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    setMarketLinkRequestOpts(requestParameters: SetMarketLinkOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Set a market link
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} commercialProductId 
     * @param {SetMarketLinkRequest} setMarketLinkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    setMarketLinkRaw(requestParameters: SetMarketLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Set a market link
     */
    setMarketLink(requestParameters: SetMarketLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for updateCommercialPartner without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} partnerId 
     * @param {UpdateCommercialPartnerRequest} updateCommercialPartnerRequest 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    updateCommercialPartnerRequestOpts(requestParameters: UpdateCommercialPartnerOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update a commercial partner
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} partnerId 
     * @param {UpdateCommercialPartnerRequest} updateCommercialPartnerRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    updateCommercialPartnerRaw(requestParameters: UpdateCommercialPartnerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Update a commercial partner
     */
    updateCommercialPartner(requestParameters: UpdateCommercialPartnerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for updateCommercialProduct without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} commercialProductId 
     * @param {UpdateCommercialProductRequest} updateCommercialProductRequest 
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    updateCommercialProductRequestOpts(requestParameters: UpdateCommercialProductOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update a commercial product
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} commercialProductId 
     * @param {UpdateCommercialProductRequest} updateCommercialProductRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialCatalogApiInterface
     */
    updateCommercialProductRaw(requestParameters: UpdateCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Update a commercial product
     */
    updateCommercialProduct(requestParameters: UpdateCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

}

/**
 * 
 */
export class CommercialCatalogApi extends runtime.BaseAPI implements CommercialCatalogApiInterface {

    /**
     * Creates request options for archiveCommercialProduct without sending the request
     */
    async archiveCommercialProductRequestOpts(requestParameters: ArchiveCommercialProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling archiveCommercialProduct().'
            );
        }

        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling archiveCommercialProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/products/{productId}/archive`;
        urlPath = urlPath.replace('{productId}', encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Archive a commercial product
     */
    async archiveCommercialProductRaw(requestParameters: ArchiveCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommercialProductLifecycleEnvelope>> {
        const requestOptions = await this.archiveCommercialProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommercialProductLifecycleEnvelopeFromJSON(jsonValue));
    }

    /**
     * Archive a commercial product
     */
    async archiveCommercialProduct(requestParameters: ArchiveCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommercialProductLifecycleEnvelope> {
        const response = await this.archiveCommercialProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createCommercialPartner without sending the request
     */
    async createCommercialPartnerRequestOpts(requestParameters: CreateCommercialPartnerOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createCommercialPartner().'
            );
        }

        if (requestParameters['createCommercialPartnerRequest'] == null) {
            throw new runtime.RequiredError(
                'createCommercialPartnerRequest',
                'Required parameter "createCommercialPartnerRequest" was null or undefined when calling createCommercialPartner().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/partners`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCommercialPartnerRequestToJSON(requestParameters['createCommercialPartnerRequest']),
        };
    }

    /**
     * Create a commercial partner
     */
    async createCommercialPartnerRaw(requestParameters: CreateCommercialPartnerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.createCommercialPartnerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create a commercial partner
     */
    async createCommercialPartner(requestParameters: CreateCommercialPartnerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.createCommercialPartnerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createCommercialProduct without sending the request
     */
    async createCommercialProductRequestOpts(requestParameters: CreateCommercialProductOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createCommercialProduct().'
            );
        }

        if (requestParameters['createCommercialProductRequest'] == null) {
            throw new runtime.RequiredError(
                'createCommercialProductRequest',
                'Required parameter "createCommercialProductRequest" was null or undefined when calling createCommercialProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/products`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCommercialProductRequestToJSON(requestParameters['createCommercialProductRequest']),
        };
    }

    /**
     * Create a commercial product
     */
    async createCommercialProductRaw(requestParameters: CreateCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.createCommercialProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create a commercial product
     */
    async createCommercialProduct(requestParameters: CreateCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.createCommercialProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCommercialProduct without sending the request
     */
    async deleteCommercialProductRequestOpts(requestParameters: DeleteCommercialProductOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling deleteCommercialProduct().'
            );
        }

        if (requestParameters['commercialProductId'] == null) {
            throw new runtime.RequiredError(
                'commercialProductId',
                'Required parameter "commercialProductId" was null or undefined when calling deleteCommercialProduct().'
            );
        }

        if (requestParameters['deleteCommercialProductRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteCommercialProductRequest',
                'Required parameter "deleteCommercialProductRequest" was null or undefined when calling deleteCommercialProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/products/{commercial_product_id}`;
        urlPath = urlPath.replace('{commercial_product_id}', encodeURIComponent(String(requestParameters['commercialProductId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteCommercialProductRequestToJSON(requestParameters['deleteCommercialProductRequest']),
        };
    }

    /**
     * Delete a commercial product
     */
    async deleteCommercialProductRaw(requestParameters: DeleteCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.deleteCommercialProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete a commercial product
     */
    async deleteCommercialProduct(requestParameters: DeleteCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.deleteCommercialProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteMarketLink without sending the request
     */
    async deleteMarketLinkRequestOpts(requestParameters: DeleteMarketLinkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling deleteMarketLink().'
            );
        }

        if (requestParameters['commercialProductId'] == null) {
            throw new runtime.RequiredError(
                'commercialProductId',
                'Required parameter "commercialProductId" was null or undefined when calling deleteMarketLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/products/{commercial_product_id}/market-link`;
        urlPath = urlPath.replace('{commercial_product_id}', encodeURIComponent(String(requestParameters['commercialProductId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a market link
     */
    async deleteMarketLinkRaw(requestParameters: DeleteMarketLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.deleteMarketLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Remove a market link
     */
    async deleteMarketLink(requestParameters: DeleteMarketLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.deleteMarketLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommercialPartner without sending the request
     */
    async getCommercialPartnerRequestOpts(requestParameters: GetCommercialPartnerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['partnerId'] == null) {
            throw new runtime.RequiredError(
                'partnerId',
                'Required parameter "partnerId" was null or undefined when calling getCommercialPartner().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/partners/{partner_id}`;
        urlPath = urlPath.replace('{partner_id}', encodeURIComponent(String(requestParameters['partnerId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a commercial partner
     */
    async getCommercialPartnerRaw(requestParameters: GetCommercialPartnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getCommercialPartnerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get a commercial partner
     */
    async getCommercialPartner(requestParameters: GetCommercialPartnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getCommercialPartnerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommercialProduct without sending the request
     */
    async getCommercialProductRequestOpts(requestParameters: GetCommercialProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commercialProductId'] == null) {
            throw new runtime.RequiredError(
                'commercialProductId',
                'Required parameter "commercialProductId" was null or undefined when calling getCommercialProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/products/{commercial_product_id}`;
        urlPath = urlPath.replace('{commercial_product_id}', encodeURIComponent(String(requestParameters['commercialProductId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a commercial product
     */
    async getCommercialProductRaw(requestParameters: GetCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getCommercialProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get a commercial product
     */
    async getCommercialProduct(requestParameters: GetCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getCommercialProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMarketLink without sending the request
     */
    async getMarketLinkRequestOpts(requestParameters: GetMarketLinkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commercialProductId'] == null) {
            throw new runtime.RequiredError(
                'commercialProductId',
                'Required parameter "commercialProductId" was null or undefined when calling getMarketLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/products/{commercial_product_id}/market-link`;
        urlPath = urlPath.replace('{commercial_product_id}', encodeURIComponent(String(requestParameters['commercialProductId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a market link
     */
    async getMarketLinkRaw(requestParameters: GetMarketLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getMarketLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get a market link
     */
    async getMarketLink(requestParameters: GetMarketLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getMarketLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCommercialPartners without sending the request
     */
    async listCommercialPartnersRequestOpts(requestParameters: ListCommercialPartnersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['role'] != null) {
            queryParameters['role'] = requestParameters['role'];
        }

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortDirection'] != null) {
            queryParameters['sortDirection'] = requestParameters['sortDirection'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/partners`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List commercial partners
     */
    async listCommercialPartnersRaw(requestParameters: ListCommercialPartnersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listCommercialPartnersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List commercial partners
     */
    async listCommercialPartners(requestParameters: ListCommercialPartnersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listCommercialPartnersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCommercialProducts without sending the request
     */
    async listCommercialProductsRequestOpts(requestParameters: ListCommercialProductsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['matchState'] != null) {
            queryParameters['matchState'] = requestParameters['matchState'];
        }

        if (requestParameters['brands'] != null) {
            queryParameters['brands'] = requestParameters['brands'];
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories'] = requestParameters['categories'];
        }

        if (requestParameters['stockMin'] != null) {
            queryParameters['stockMin'] = requestParameters['stockMin'];
        }

        if (requestParameters['stockMax'] != null) {
            queryParameters['stockMax'] = requestParameters['stockMax'];
        }

        if (requestParameters['moneyField'] != null) {
            queryParameters['moneyField'] = requestParameters['moneyField'];
        }

        if (requestParameters['moneyMin'] != null) {
            queryParameters['moneyMin'] = requestParameters['moneyMin'];
        }

        if (requestParameters['moneyMax'] != null) {
            queryParameters['moneyMax'] = requestParameters['moneyMax'];
        }

        if (requestParameters['moneyCurrency'] != null) {
            queryParameters['moneyCurrency'] = requestParameters['moneyCurrency'];
        }

        if (requestParameters['smartFilters'] != null) {
            queryParameters['smartFilters'] = requestParameters['smartFilters'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortDirection'] != null) {
            queryParameters['sortDirection'] = requestParameters['sortDirection'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/products`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List commercial products
     */
    async listCommercialProductsRaw(requestParameters: ListCommercialProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listCommercialProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List commercial products
     */
    async listCommercialProducts(requestParameters: ListCommercialProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listCommercialProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for restoreCommercialProduct without sending the request
     */
    async restoreCommercialProductRequestOpts(requestParameters: RestoreCommercialProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling restoreCommercialProduct().'
            );
        }

        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling restoreCommercialProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/products/{productId}/restore`;
        urlPath = urlPath.replace('{productId}', encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Restore a commercial product
     */
    async restoreCommercialProductRaw(requestParameters: RestoreCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommercialProductLifecycleEnvelope>> {
        const requestOptions = await this.restoreCommercialProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommercialProductLifecycleEnvelopeFromJSON(jsonValue));
    }

    /**
     * Restore a commercial product
     */
    async restoreCommercialProduct(requestParameters: RestoreCommercialProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommercialProductLifecycleEnvelope> {
        const response = await this.restoreCommercialProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setMarketLink without sending the request
     */
    async setMarketLinkRequestOpts(requestParameters: SetMarketLinkOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling setMarketLink().'
            );
        }

        if (requestParameters['commercialProductId'] == null) {
            throw new runtime.RequiredError(
                'commercialProductId',
                'Required parameter "commercialProductId" was null or undefined when calling setMarketLink().'
            );
        }

        if (requestParameters['setMarketLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'setMarketLinkRequest',
                'Required parameter "setMarketLinkRequest" was null or undefined when calling setMarketLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/products/{commercial_product_id}/market-link`;
        urlPath = urlPath.replace('{commercial_product_id}', encodeURIComponent(String(requestParameters['commercialProductId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetMarketLinkRequestToJSON(requestParameters['setMarketLinkRequest']),
        };
    }

    /**
     * Set a market link
     */
    async setMarketLinkRaw(requestParameters: SetMarketLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.setMarketLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Set a market link
     */
    async setMarketLink(requestParameters: SetMarketLinkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.setMarketLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCommercialPartner without sending the request
     */
    async updateCommercialPartnerRequestOpts(requestParameters: UpdateCommercialPartnerOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateCommercialPartner().'
            );
        }

        if (requestParameters['partnerId'] == null) {
            throw new runtime.RequiredError(
                'partnerId',
                'Required parameter "partnerId" was null or undefined when calling updateCommercialPartner().'
            );
        }

        if (requestParameters['updateCommercialPartnerRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCommercialPartnerRequest',
                'Required parameter "updateCommercialPartnerRequest" was null or undefined when calling updateCommercialPartner().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/partners/{partner_id}`;
        urlPath = urlPath.replace('{partner_id}', encodeURIComponent(String(requestParameters['partnerId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCommercialPartnerRequestToJSON(requestParameters['updateCommercialPartnerRequest']),
        };
    }

    /**
     * Update a commercial partner
     */
    async updateCommercialPartnerRaw(requestParameters: UpdateCommercialPartnerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.updateCommercialPartnerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Update a commercial partner
     */
    async updateCommercialPartner(requestParameters: UpdateCommercialPartnerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.updateCommercialPartnerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCommercialProduct without sending the request
     */
    async updateCommercialProductRequestOpts(requestParameters: UpdateCommercialProductOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateCommercialProduct().'
            );
        }

        if (requestParameters['commercialProductId'] == null) {
            throw new runtime.RequiredError(
                'commercialProductId',
                'Required parameter "commercialProductId" was null or undefined when calling updateCommercialProduct().'
            );
        }

        if (requestParameters['updateCommercialProductRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCommercialProductRequest',
                'Required parameter "updateCommercialProductRequest" was null or undefined when calling updateCommercialProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/products/{commercial_product_id}`;
        urlPath = urlPath.replace('{commercial_product_id}', encodeURIComponent(String(requestParameters['commercialProductId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCommercialProductRequestToJSON(requestParameters['updateCommercialProductRequest']),
        };
    }

    /**
     * Update a commercial product
     */
    async updateCommercialProductRaw(requestParameters: UpdateCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.updateCommercialProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Update a commercial product
     */
    async updateCommercialProduct(requestParameters: UpdateCommercialProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.updateCommercialProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
