/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AcceptedEnvelope,
    AcceptedEnvelopeFromJSON,
    AcceptedEnvelopeToJSON,
} from '../models/AcceptedEnvelope';
import {
    type CreateCommercialImportRequest,
    CreateCommercialImportRequestFromJSON,
    CreateCommercialImportRequestToJSON,
} from '../models/CreateCommercialImportRequest';
import {
    type DataEnvelope,
    DataEnvelopeFromJSON,
    DataEnvelopeToJSON,
} from '../models/DataEnvelope';
import {
    type ListEnvelope,
    ListEnvelopeFromJSON,
    ListEnvelopeToJSON,
} from '../models/ListEnvelope';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface CancelCommercialImportRequest {
    idempotencyKey: string;
    importId: string;
}

export interface CreateCommercialImportOperationRequest {
    idempotencyKey: string;
    createCommercialImportRequest: CreateCommercialImportRequest;
}

export interface ListCommercialImportsRequest {
    page?: number;
    size?: number;
    search?: string;
    kind?: string;
    status?: string;
    dryRun?: boolean | null;
    sortBy?: string;
    sortDirection?: string;
}

/**
 * CommercialImportsApi - interface
 * 
 * @export
 * @interface CommercialImportsApiInterface
 */
export interface CommercialImportsApiInterface {
    /**
     * Creates request options for cancelCommercialImport without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} importId 
     * @throws {RequiredError}
     * @memberof CommercialImportsApiInterface
     */
    cancelCommercialImportRequestOpts(requestParameters: CancelCommercialImportRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Cancel a commercial import
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} importId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialImportsApiInterface
     */
    cancelCommercialImportRaw(requestParameters: CancelCommercialImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Cancel a commercial import
     */
    cancelCommercialImport(requestParameters: CancelCommercialImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for createCommercialImport without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateCommercialImportRequest} createCommercialImportRequest 
     * @throws {RequiredError}
     * @memberof CommercialImportsApiInterface
     */
    createCommercialImportRequestOpts(requestParameters: CreateCommercialImportOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a commercial import
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateCommercialImportRequest} createCommercialImportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialImportsApiInterface
     */
    createCommercialImportRaw(requestParameters: CreateCommercialImportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptedEnvelope>>;

    /**
     * Create a commercial import
     */
    createCommercialImport(requestParameters: CreateCommercialImportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptedEnvelope>;

    /**
     * Creates request options for listCommercialImports without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {string} [kind] 
     * @param {string} [status] 
     * @param {boolean} [dryRun] 
     * @param {string} [sortBy] 
     * @param {string} [sortDirection] 
     * @throws {RequiredError}
     * @memberof CommercialImportsApiInterface
     */
    listCommercialImportsRequestOpts(requestParameters: ListCommercialImportsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List commercial imports
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {string} [kind] 
     * @param {string} [status] 
     * @param {boolean} [dryRun] 
     * @param {string} [sortBy] 
     * @param {string} [sortDirection] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommercialImportsApiInterface
     */
    listCommercialImportsRaw(requestParameters: ListCommercialImportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List commercial imports
     */
    listCommercialImports(requestParameters: ListCommercialImportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

}

/**
 * 
 */
export class CommercialImportsApi extends runtime.BaseAPI implements CommercialImportsApiInterface {

    /**
     * Creates request options for cancelCommercialImport without sending the request
     */
    async cancelCommercialImportRequestOpts(requestParameters: CancelCommercialImportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling cancelCommercialImport().'
            );
        }

        if (requestParameters['importId'] == null) {
            throw new runtime.RequiredError(
                'importId',
                'Required parameter "importId" was null or undefined when calling cancelCommercialImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_imports:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/imports/{import_id}/cancel`;
        urlPath = urlPath.replace('{import_id}', encodeURIComponent(String(requestParameters['importId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel a commercial import
     */
    async cancelCommercialImportRaw(requestParameters: CancelCommercialImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.cancelCommercialImportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Cancel a commercial import
     */
    async cancelCommercialImport(requestParameters: CancelCommercialImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.cancelCommercialImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createCommercialImport without sending the request
     */
    async createCommercialImportRequestOpts(requestParameters: CreateCommercialImportOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createCommercialImport().'
            );
        }

        if (requestParameters['createCommercialImportRequest'] == null) {
            throw new runtime.RequiredError(
                'createCommercialImportRequest',
                'Required parameter "createCommercialImportRequest" was null or undefined when calling createCommercialImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_imports:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/imports`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCommercialImportRequestToJSON(requestParameters['createCommercialImportRequest']),
        };
    }

    /**
     * Create a commercial import
     */
    async createCommercialImportRaw(requestParameters: CreateCommercialImportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptedEnvelope>> {
        const requestOptions = await this.createCommercialImportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AcceptedEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create a commercial import
     */
    async createCommercialImport(requestParameters: CreateCommercialImportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptedEnvelope> {
        const response = await this.createCommercialImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCommercialImports without sending the request
     */
    async listCommercialImportsRequestOpts(requestParameters: ListCommercialImportsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['kind'] != null) {
            queryParameters['kind'] = requestParameters['kind'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['dryRun'] != null) {
            queryParameters['dryRun'] = requestParameters['dryRun'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortDirection'] != null) {
            queryParameters['sortDirection'] = requestParameters['sortDirection'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["commercial_imports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/commercial/imports`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List commercial imports
     */
    async listCommercialImportsRaw(requestParameters: ListCommercialImportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listCommercialImportsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List commercial imports
     */
    async listCommercialImports(requestParameters: ListCommercialImportsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listCommercialImportsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
