/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DataEnvelope,
    DataEnvelopeFromJSON,
    DataEnvelopeToJSON,
} from '../models/DataEnvelope';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

/**
 * ContextApi - interface
 * 
 * @export
 * @interface ContextApiInterface
 */
export interface ContextApiInterface {
    /**
     * Creates request options for getContext without sending the request
     * @throws {RequiredError}
     * @memberof ContextApiInterface
     */
    getContextRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get API principal context
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContextApiInterface
     */
    getContextRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get API principal context
     */
    getContext(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

}

/**
 * 
 */
export class ContextApi extends runtime.BaseAPI implements ContextApiInterface {

    /**
     * Creates request options for getContext without sending the request
     */
    async getContextRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["stores:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/context`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get API principal context
     */
    async getContextRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getContextRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get API principal context
     */
    async getContext(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getContextRaw(initOverrides);
        return await response.value();
    }

}
