/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AcceptedEnvelope,
    AcceptedEnvelopeFromJSON,
    AcceptedEnvelopeToJSON,
} from '../models/AcceptedEnvelope';
import {
    type CreateExportRequest,
    CreateExportRequestFromJSON,
    CreateExportRequestToJSON,
} from '../models/CreateExportRequest';
import {
    type DataEnvelope,
    DataEnvelopeFromJSON,
    DataEnvelopeToJSON,
} from '../models/DataEnvelope';
import {
    type EstimateExportRequest,
    EstimateExportRequestFromJSON,
    EstimateExportRequestToJSON,
} from '../models/EstimateExportRequest';
import {
    type ListEnvelope,
    ListEnvelopeFromJSON,
    ListEnvelopeToJSON,
} from '../models/ListEnvelope';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface CancelExportRequest {
    idempotencyKey: string;
    exportId: string;
}

export interface CreateExportOperationRequest {
    idempotencyKey: string;
    createExportRequest: CreateExportRequest;
}

export interface DownloadExportRequest {
    exportId: string;
}

export interface EstimateExportOperationRequest {
    idempotencyKey: string;
    estimateExportRequest: EstimateExportRequest;
}

export interface GetExportRequest {
    exportId: string;
}

export interface ListExportsRequest {
    cursor?: string;
    limit?: number;
    scope?: string;
    search?: string;
    status?: string;
    dataset?: string;
    format?: string;
    createdFrom?: Date;
    createdTo?: Date;
}

export interface RetryExportRequest {
    idempotencyKey: string;
    exportId: string;
}

/**
 * ExportsApi - interface
 * 
 * @export
 * @interface ExportsApiInterface
 */
export interface ExportsApiInterface {
    /**
     * Creates request options for cancelExport without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} exportId 
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    cancelExportRequestOpts(requestParameters: CancelExportRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Cancel an export
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} exportId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    cancelExportRaw(requestParameters: CancelExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Cancel an export
     */
    cancelExport(requestParameters: CancelExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for createExport without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateExportRequest} createExportRequest 
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    createExportRequestOpts(requestParameters: CreateExportOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create an export
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateExportRequest} createExportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    createExportRaw(requestParameters: CreateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptedEnvelope>>;

    /**
     * Create an export
     */
    createExport(requestParameters: CreateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptedEnvelope>;

    /**
     * Creates request options for downloadExport without sending the request
     * @param {string} exportId 
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    downloadExportRequestOpts(requestParameters: DownloadExportRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Download a completed export
     * @param {string} exportId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    downloadExportRaw(requestParameters: DownloadExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Download a completed export
     */
    downloadExport(requestParameters: DownloadExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for estimateExport without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {EstimateExportRequest} estimateExportRequest 
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    estimateExportRequestOpts(requestParameters: EstimateExportOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Estimate an export
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {EstimateExportRequest} estimateExportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    estimateExportRaw(requestParameters: EstimateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Estimate an export
     */
    estimateExport(requestParameters: EstimateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getExport without sending the request
     * @param {string} exportId 
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    getExportRequestOpts(requestParameters: GetExportRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get an export
     * @param {string} exportId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    getExportRaw(requestParameters: GetExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get an export
     */
    getExport(requestParameters: GetExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for listExports without sending the request
     * @param {string} [cursor] 
     * @param {number} [limit] 
     * @param {string} [scope] 
     * @param {string} [search] 
     * @param {string} [status] 
     * @param {string} [dataset] 
     * @param {string} [format] 
     * @param {Date} [createdFrom] 
     * @param {Date} [createdTo] 
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    listExportsRequestOpts(requestParameters: ListExportsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List exports
     * @param {string} [cursor] 
     * @param {number} [limit] 
     * @param {string} [scope] 
     * @param {string} [search] 
     * @param {string} [status] 
     * @param {string} [dataset] 
     * @param {string} [format] 
     * @param {Date} [createdFrom] 
     * @param {Date} [createdTo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    listExportsRaw(requestParameters: ListExportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List exports
     */
    listExports(requestParameters: ListExportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for retryExport without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} exportId 
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    retryExportRequestOpts(requestParameters: RetryExportRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Retry an export
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} exportId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportsApiInterface
     */
    retryExportRaw(requestParameters: RetryExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Retry an export
     */
    retryExport(requestParameters: RetryExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

}

/**
 * 
 */
export class ExportsApi extends runtime.BaseAPI implements ExportsApiInterface {

    /**
     * Creates request options for cancelExport without sending the request
     */
    async cancelExportRequestOpts(requestParameters: CancelExportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling cancelExport().'
            );
        }

        if (requestParameters['exportId'] == null) {
            throw new runtime.RequiredError(
                'exportId',
                'Required parameter "exportId" was null or undefined when calling cancelExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["exports:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/exports/{export_id}/cancel`;
        urlPath = urlPath.replace('{export_id}', encodeURIComponent(String(requestParameters['exportId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel an export
     */
    async cancelExportRaw(requestParameters: CancelExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.cancelExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Cancel an export
     */
    async cancelExport(requestParameters: CancelExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.cancelExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createExport without sending the request
     */
    async createExportRequestOpts(requestParameters: CreateExportOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createExport().'
            );
        }

        if (requestParameters['createExportRequest'] == null) {
            throw new runtime.RequiredError(
                'createExportRequest',
                'Required parameter "createExportRequest" was null or undefined when calling createExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["exports:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/exports`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateExportRequestToJSON(requestParameters['createExportRequest']),
        };
    }

    /**
     * Create an export
     */
    async createExportRaw(requestParameters: CreateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptedEnvelope>> {
        const requestOptions = await this.createExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AcceptedEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create an export
     */
    async createExport(requestParameters: CreateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptedEnvelope> {
        const response = await this.createExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadExport without sending the request
     */
    async downloadExportRequestOpts(requestParameters: DownloadExportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['exportId'] == null) {
            throw new runtime.RequiredError(
                'exportId',
                'Required parameter "exportId" was null or undefined when calling downloadExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/exports/{export_id}/download`;
        urlPath = urlPath.replace('{export_id}', encodeURIComponent(String(requestParameters['exportId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download a completed export
     */
    async downloadExportRaw(requestParameters: DownloadExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.downloadExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Download a completed export
     */
    async downloadExport(requestParameters: DownloadExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.downloadExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for estimateExport without sending the request
     */
    async estimateExportRequestOpts(requestParameters: EstimateExportOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling estimateExport().'
            );
        }

        if (requestParameters['estimateExportRequest'] == null) {
            throw new runtime.RequiredError(
                'estimateExportRequest',
                'Required parameter "estimateExportRequest" was null or undefined when calling estimateExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/exports/estimate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EstimateExportRequestToJSON(requestParameters['estimateExportRequest']),
        };
    }

    /**
     * Estimate an export
     */
    async estimateExportRaw(requestParameters: EstimateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.estimateExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Estimate an export
     */
    async estimateExport(requestParameters: EstimateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.estimateExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExport without sending the request
     */
    async getExportRequestOpts(requestParameters: GetExportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['exportId'] == null) {
            throw new runtime.RequiredError(
                'exportId',
                'Required parameter "exportId" was null or undefined when calling getExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/exports/{export_id}`;
        urlPath = urlPath.replace('{export_id}', encodeURIComponent(String(requestParameters['exportId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get an export
     */
    async getExportRaw(requestParameters: GetExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get an export
     */
    async getExport(requestParameters: GetExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listExports without sending the request
     */
    async listExportsRequestOpts(requestParameters: ListExportsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['dataset'] != null) {
            queryParameters['dataset'] = requestParameters['dataset'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['createdFrom'] != null) {
            queryParameters['createdFrom'] = (requestParameters['createdFrom'] as any).toISOString();
        }

        if (requestParameters['createdTo'] != null) {
            queryParameters['createdTo'] = (requestParameters['createdTo'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/exports`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List exports
     */
    async listExportsRaw(requestParameters: ListExportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listExportsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List exports
     */
    async listExports(requestParameters: ListExportsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listExportsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retryExport without sending the request
     */
    async retryExportRequestOpts(requestParameters: RetryExportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling retryExport().'
            );
        }

        if (requestParameters['exportId'] == null) {
            throw new runtime.RequiredError(
                'exportId',
                'Required parameter "exportId" was null or undefined when calling retryExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["exports:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/exports/{export_id}/retry`;
        urlPath = urlPath.replace('{export_id}', encodeURIComponent(String(requestParameters['exportId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retry an export
     */
    async retryExportRaw(requestParameters: RetryExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.retryExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Retry an export
     */
    async retryExport(requestParameters: RetryExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.retryExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
