/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateReportRequest,
    CreateReportRequestFromJSON,
    CreateReportRequestToJSON,
} from '../models/CreateReportRequest';
import {
    type DataEnvelope,
    DataEnvelopeFromJSON,
    DataEnvelopeToJSON,
} from '../models/DataEnvelope';
import {
    type ListEnvelope,
    ListEnvelopeFromJSON,
    ListEnvelopeToJSON,
} from '../models/ListEnvelope';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type UpdateReportRequest,
    UpdateReportRequestFromJSON,
    UpdateReportRequestToJSON,
} from '../models/UpdateReportRequest';

export interface CreateReportOperationRequest {
    idempotencyKey: string;
    createReportRequest: CreateReportRequest;
}

export interface CreateReportRunRequest {
    idempotencyKey: string;
    reportId: string;
}

export interface DeleteReportRequest {
    idempotencyKey: string;
    reportId: string;
}

export interface DownloadReportRunRequest {
    reportRunId: string;
}

export interface GetReportRequest {
    reportId: string;
}

export interface ListReportRunsRequest {
    reportId: string;
}

export interface ListReportsRequest {
    page?: number;
    size?: number;
    search?: string;
    status?: string;
    type?: string;
    isActive?: boolean | null;
    scheduled?: boolean | null;
}

export interface UpdateReportOperationRequest {
    idempotencyKey: string;
    reportId: string;
    updateReportRequest: UpdateReportRequest;
}

/**
 * ReportsApi - interface
 * 
 * @export
 * @interface ReportsApiInterface
 */
export interface ReportsApiInterface {
    /**
     * Creates request options for createReport without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateReportRequest} createReportRequest 
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    createReportRequestOpts(requestParameters: CreateReportOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a report definition
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateReportRequest} createReportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    createReportRaw(requestParameters: CreateReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Create a report definition
     */
    createReport(requestParameters: CreateReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for createReportRun without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} reportId 
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    createReportRunRequestOpts(requestParameters: CreateReportRunRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Start a report run
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} reportId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    createReportRunRaw(requestParameters: CreateReportRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Start a report run
     */
    createReportRun(requestParameters: CreateReportRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for deleteReport without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} reportId 
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    deleteReportRequestOpts(requestParameters: DeleteReportRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Retire a report definition and retain its history
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} reportId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    deleteReportRaw(requestParameters: DeleteReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Retire a report definition and retain its history
     */
    deleteReport(requestParameters: DeleteReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for downloadReportRun without sending the request
     * @param {string} reportRunId 
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    downloadReportRunRequestOpts(requestParameters: DownloadReportRunRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Download a completed report
     * @param {string} reportRunId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    downloadReportRunRaw(requestParameters: DownloadReportRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Download a completed report
     */
    downloadReportRun(requestParameters: DownloadReportRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getReport without sending the request
     * @param {string} reportId 
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    getReportRequestOpts(requestParameters: GetReportRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a report definition
     * @param {string} reportId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    getReportRaw(requestParameters: GetReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get a report definition
     */
    getReport(requestParameters: GetReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for listReportRuns without sending the request
     * @param {string} reportId 
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    listReportRunsRequestOpts(requestParameters: ListReportRunsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List report generation attempts
     * @param {string} reportId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    listReportRunsRaw(requestParameters: ListReportRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List report generation attempts
     */
    listReportRuns(requestParameters: ListReportRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for listReports without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {string} [status] 
     * @param {string} [type] 
     * @param {boolean} [isActive] 
     * @param {boolean} [scheduled] 
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    listReportsRequestOpts(requestParameters: ListReportsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List report definitions
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [search] 
     * @param {string} [status] 
     * @param {string} [type] 
     * @param {boolean} [isActive] 
     * @param {boolean} [scheduled] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    listReportsRaw(requestParameters: ListReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List report definitions
     */
    listReports(requestParameters: ListReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for updateReport without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} reportId 
     * @param {UpdateReportRequest} updateReportRequest 
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    updateReportRequestOpts(requestParameters: UpdateReportOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update a report definition
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} reportId 
     * @param {UpdateReportRequest} updateReportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsApiInterface
     */
    updateReportRaw(requestParameters: UpdateReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Update a report definition
     */
    updateReport(requestParameters: UpdateReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

}

/**
 * 
 */
export class ReportsApi extends runtime.BaseAPI implements ReportsApiInterface {

    /**
     * Creates request options for createReport without sending the request
     */
    async createReportRequestOpts(requestParameters: CreateReportOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createReport().'
            );
        }

        if (requestParameters['createReportRequest'] == null) {
            throw new runtime.RequiredError(
                'createReportRequest',
                'Required parameter "createReportRequest" was null or undefined when calling createReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["reports:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/reports`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateReportRequestToJSON(requestParameters['createReportRequest']),
        };
    }

    /**
     * Create a report definition
     */
    async createReportRaw(requestParameters: CreateReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.createReportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create a report definition
     */
    async createReport(requestParameters: CreateReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.createReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createReportRun without sending the request
     */
    async createReportRunRequestOpts(requestParameters: CreateReportRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createReportRun().'
            );
        }

        if (requestParameters['reportId'] == null) {
            throw new runtime.RequiredError(
                'reportId',
                'Required parameter "reportId" was null or undefined when calling createReportRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["reports:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/reports/{report_id}/runs`;
        urlPath = urlPath.replace('{report_id}', encodeURIComponent(String(requestParameters['reportId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Start a report run
     */
    async createReportRunRaw(requestParameters: CreateReportRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.createReportRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Start a report run
     */
    async createReportRun(requestParameters: CreateReportRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.createReportRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteReport without sending the request
     */
    async deleteReportRequestOpts(requestParameters: DeleteReportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling deleteReport().'
            );
        }

        if (requestParameters['reportId'] == null) {
            throw new runtime.RequiredError(
                'reportId',
                'Required parameter "reportId" was null or undefined when calling deleteReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["reports:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/reports/{report_id}`;
        urlPath = urlPath.replace('{report_id}', encodeURIComponent(String(requestParameters['reportId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retire a report definition and retain its history
     */
    async deleteReportRaw(requestParameters: DeleteReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.deleteReportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Retire a report definition and retain its history
     */
    async deleteReport(requestParameters: DeleteReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.deleteReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadReportRun without sending the request
     */
    async downloadReportRunRequestOpts(requestParameters: DownloadReportRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reportRunId'] == null) {
            throw new runtime.RequiredError(
                'reportRunId',
                'Required parameter "reportRunId" was null or undefined when calling downloadReportRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["reports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/report-runs/{report_run_id}/download`;
        urlPath = urlPath.replace('{report_run_id}', encodeURIComponent(String(requestParameters['reportRunId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download a completed report
     */
    async downloadReportRunRaw(requestParameters: DownloadReportRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.downloadReportRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Download a completed report
     */
    async downloadReportRun(requestParameters: DownloadReportRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.downloadReportRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getReport without sending the request
     */
    async getReportRequestOpts(requestParameters: GetReportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reportId'] == null) {
            throw new runtime.RequiredError(
                'reportId',
                'Required parameter "reportId" was null or undefined when calling getReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["reports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/reports/{report_id}`;
        urlPath = urlPath.replace('{report_id}', encodeURIComponent(String(requestParameters['reportId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a report definition
     */
    async getReportRaw(requestParameters: GetReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getReportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get a report definition
     */
    async getReport(requestParameters: GetReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listReportRuns without sending the request
     */
    async listReportRunsRequestOpts(requestParameters: ListReportRunsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reportId'] == null) {
            throw new runtime.RequiredError(
                'reportId',
                'Required parameter "reportId" was null or undefined when calling listReportRuns().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["reports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/reports/{report_id}/runs`;
        urlPath = urlPath.replace('{report_id}', encodeURIComponent(String(requestParameters['reportId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List report generation attempts
     */
    async listReportRunsRaw(requestParameters: ListReportRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listReportRunsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List report generation attempts
     */
    async listReportRuns(requestParameters: ListReportRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listReportRunsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listReports without sending the request
     */
    async listReportsRequestOpts(requestParameters: ListReportsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['isActive'] != null) {
            queryParameters['isActive'] = requestParameters['isActive'];
        }

        if (requestParameters['scheduled'] != null) {
            queryParameters['scheduled'] = requestParameters['scheduled'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["reports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/reports`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List report definitions
     */
    async listReportsRaw(requestParameters: ListReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listReportsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List report definitions
     */
    async listReports(requestParameters: ListReportsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listReportsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateReport without sending the request
     */
    async updateReportRequestOpts(requestParameters: UpdateReportOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateReport().'
            );
        }

        if (requestParameters['reportId'] == null) {
            throw new runtime.RequiredError(
                'reportId',
                'Required parameter "reportId" was null or undefined when calling updateReport().'
            );
        }

        if (requestParameters['updateReportRequest'] == null) {
            throw new runtime.RequiredError(
                'updateReportRequest',
                'Required parameter "updateReportRequest" was null or undefined when calling updateReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["reports:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/reports/{report_id}`;
        urlPath = urlPath.replace('{report_id}', encodeURIComponent(String(requestParameters['reportId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateReportRequestToJSON(requestParameters['updateReportRequest']),
        };
    }

    /**
     * Update a report definition
     */
    async updateReportRaw(requestParameters: UpdateReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.updateReportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Update a report definition
     */
    async updateReport(requestParameters: UpdateReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.updateReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
