/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AcceptedEnvelope,
    AcceptedEnvelopeFromJSON,
    AcceptedEnvelopeToJSON,
} from '../models/AcceptedEnvelope';
import {
    type ApplyRepricerRecommendationRequest,
    ApplyRepricerRecommendationRequestFromJSON,
    ApplyRepricerRecommendationRequestToJSON,
} from '../models/ApplyRepricerRecommendationRequest';
import {
    type CreateRepricerExclusionRequest,
    CreateRepricerExclusionRequestFromJSON,
    CreateRepricerExclusionRequestToJSON,
} from '../models/CreateRepricerExclusionRequest';
import {
    type CreateRepricerPolicyRequest,
    CreateRepricerPolicyRequestFromJSON,
    CreateRepricerPolicyRequestToJSON,
} from '../models/CreateRepricerPolicyRequest';
import {
    type DataEnvelope,
    DataEnvelopeFromJSON,
    DataEnvelopeToJSON,
} from '../models/DataEnvelope';
import {
    type ListEnvelope,
    ListEnvelopeFromJSON,
    ListEnvelopeToJSON,
} from '../models/ListEnvelope';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type UpdateRepricerSettingsRequest,
    UpdateRepricerSettingsRequestFromJSON,
    UpdateRepricerSettingsRequestToJSON,
} from '../models/UpdateRepricerSettingsRequest';

export interface ApplyRepricerRecommendationOperationRequest {
    idempotencyKey: string;
    recommendationId: string;
    applyRepricerRecommendationRequest: ApplyRepricerRecommendationRequest;
}

export interface CreateRepricerExclusionOperationRequest {
    idempotencyKey: string;
    createRepricerExclusionRequest: CreateRepricerExclusionRequest;
}

export interface CreateRepricerPolicyOperationRequest {
    idempotencyKey: string;
    createRepricerPolicyRequest: CreateRepricerPolicyRequest;
}

export interface CreateRepricerRunRequest {
    idempotencyKey: string;
}

export interface DeleteRepricerExclusionRequest {
    idempotencyKey: string;
    exclusionId: string;
}

export interface DeleteRepricerPolicyRequest {
    idempotencyKey: string;
    policyId: string;
}

export interface GetRepricerAnalyticsRequest {
    currency: string;
    period: string;
    policyId?: string;
    priceBookId?: string;
}

export interface ListRepricerExclusionsRequest {
    page?: number;
    size?: number;
    q?: string;
    enabled?: boolean | null;
    scopeType?: string;
    scopeTargetIds?: Array<string>;
    expiryState?: string;
    createdFrom?: Date;
    createdTo?: Date;
    sort?: string;
    direction?: string;
}

export interface ListRepricerPoliciesRequest {
    page?: number;
    size?: number;
    q?: string;
    enabled?: boolean | null;
    strategies?: Array<string>;
    scopeType?: string;
    scopeTargetIds?: Array<string>;
    priorityMin?: number | null;
    priorityMax?: number | null;
    guardrailState?: string;
    sort?: string;
    direction?: string;
}

export interface ListRepricerRecommendationsRequest {
    page?: number;
    size?: number;
    q?: string;
    status?: string;
    productIds?: Array<string>;
    policyIds?: Array<string>;
    priceBookIds?: Array<string>;
    currencies?: Array<string>;
    movement?: string;
    movePercentMin?: number | null;
    movePercentMax?: number | null;
    amountField?: string;
    amountMin?: number | null;
    amountMax?: number | null;
    evidenceMin?: number | null;
    evidenceMax?: number | null;
    createdFrom?: Date;
    createdTo?: Date;
    smartFilters?: Array<string>;
    sort?: string;
    direction?: string;
}

export interface ListRepricerRunsRequest {
    page?: number;
    size?: number;
    q?: string;
    status?: string;
    trigger?: string;
    requestedFrom?: Date;
    requestedTo?: Date;
    outcome?: string;
    sort?: string;
    direction?: string;
}

export interface RollbackRepricerApplicationRequest {
    idempotencyKey: string;
    applicationId: string;
}

export interface UpdateRepricerPolicyRequest {
    idempotencyKey: string;
    policyId: string;
    createRepricerPolicyRequest: CreateRepricerPolicyRequest;
}

export interface UpdateRepricerSettingsOperationRequest {
    idempotencyKey: string;
    updateRepricerSettingsRequest: UpdateRepricerSettingsRequest;
}

/**
 * RepricingApi - interface
 * 
 * @export
 * @interface RepricingApiInterface
 */
export interface RepricingApiInterface {
    /**
     * Creates request options for applyRepricerRecommendation without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} recommendationId 
     * @param {ApplyRepricerRecommendationRequest} applyRepricerRecommendationRequest 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    applyRepricerRecommendationRequestOpts(requestParameters: ApplyRepricerRecommendationOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Apply a repricer recommendation
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} recommendationId 
     * @param {ApplyRepricerRecommendationRequest} applyRepricerRecommendationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    applyRepricerRecommendationRaw(requestParameters: ApplyRepricerRecommendationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Apply a repricer recommendation
     */
    applyRepricerRecommendation(requestParameters: ApplyRepricerRecommendationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for createRepricerExclusion without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateRepricerExclusionRequest} createRepricerExclusionRequest 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    createRepricerExclusionRequestOpts(requestParameters: CreateRepricerExclusionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a repricer exclusion
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateRepricerExclusionRequest} createRepricerExclusionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    createRepricerExclusionRaw(requestParameters: CreateRepricerExclusionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Create a repricer exclusion
     */
    createRepricerExclusion(requestParameters: CreateRepricerExclusionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for createRepricerPolicy without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateRepricerPolicyRequest} createRepricerPolicyRequest 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    createRepricerPolicyRequestOpts(requestParameters: CreateRepricerPolicyOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a repricer policy
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateRepricerPolicyRequest} createRepricerPolicyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    createRepricerPolicyRaw(requestParameters: CreateRepricerPolicyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Create a repricer policy
     */
    createRepricerPolicy(requestParameters: CreateRepricerPolicyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for createRepricerRun without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    createRepricerRunRequestOpts(requestParameters: CreateRepricerRunRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a repricer run
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    createRepricerRunRaw(requestParameters: CreateRepricerRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptedEnvelope>>;

    /**
     * Create a repricer run
     */
    createRepricerRun(requestParameters: CreateRepricerRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptedEnvelope>;

    /**
     * Creates request options for deleteRepricerExclusion without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} exclusionId 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    deleteRepricerExclusionRequestOpts(requestParameters: DeleteRepricerExclusionRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Delete a repricer exclusion
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} exclusionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    deleteRepricerExclusionRaw(requestParameters: DeleteRepricerExclusionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Delete a repricer exclusion
     */
    deleteRepricerExclusion(requestParameters: DeleteRepricerExclusionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for deleteRepricerPolicy without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} policyId 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    deleteRepricerPolicyRequestOpts(requestParameters: DeleteRepricerPolicyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Delete a repricer policy
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} policyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    deleteRepricerPolicyRaw(requestParameters: DeleteRepricerPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Delete a repricer policy
     */
    deleteRepricerPolicy(requestParameters: DeleteRepricerPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getRepricerAnalytics without sending the request
     * @param {string} currency 
     * @param {string} period 
     * @param {string} [policyId] 
     * @param {string} [priceBookId] 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    getRepricerAnalyticsRequestOpts(requestParameters: GetRepricerAnalyticsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get repricer analytics
     * @param {string} currency 
     * @param {string} period 
     * @param {string} [policyId] 
     * @param {string} [priceBookId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    getRepricerAnalyticsRaw(requestParameters: GetRepricerAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get repricer analytics
     */
    getRepricerAnalytics(requestParameters: GetRepricerAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getRepricerSettings without sending the request
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    getRepricerSettingsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get repricer settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    getRepricerSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get repricer settings
     */
    getRepricerSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for listRepricerApplications without sending the request
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    listRepricerApplicationsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List repricer applications
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    listRepricerApplicationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List repricer applications
     */
    listRepricerApplications(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for listRepricerExclusions without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [q] 
     * @param {boolean} [enabled] 
     * @param {string} [scopeType] 
     * @param {Array<string>} [scopeTargetIds] 
     * @param {string} [expiryState] 
     * @param {Date} [createdFrom] 
     * @param {Date} [createdTo] 
     * @param {string} [sort] 
     * @param {string} [direction] 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    listRepricerExclusionsRequestOpts(requestParameters: ListRepricerExclusionsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List repricer exclusions
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [q] 
     * @param {boolean} [enabled] 
     * @param {string} [scopeType] 
     * @param {Array<string>} [scopeTargetIds] 
     * @param {string} [expiryState] 
     * @param {Date} [createdFrom] 
     * @param {Date} [createdTo] 
     * @param {string} [sort] 
     * @param {string} [direction] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    listRepricerExclusionsRaw(requestParameters: ListRepricerExclusionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List repricer exclusions
     */
    listRepricerExclusions(requestParameters: ListRepricerExclusionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for listRepricerPolicies without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [q] 
     * @param {boolean} [enabled] 
     * @param {Array<string>} [strategies] 
     * @param {string} [scopeType] 
     * @param {Array<string>} [scopeTargetIds] 
     * @param {number} [priorityMin] 
     * @param {number} [priorityMax] 
     * @param {string} [guardrailState] 
     * @param {string} [sort] 
     * @param {string} [direction] 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    listRepricerPoliciesRequestOpts(requestParameters: ListRepricerPoliciesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List repricer policies
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [q] 
     * @param {boolean} [enabled] 
     * @param {Array<string>} [strategies] 
     * @param {string} [scopeType] 
     * @param {Array<string>} [scopeTargetIds] 
     * @param {number} [priorityMin] 
     * @param {number} [priorityMax] 
     * @param {string} [guardrailState] 
     * @param {string} [sort] 
     * @param {string} [direction] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    listRepricerPoliciesRaw(requestParameters: ListRepricerPoliciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List repricer policies
     */
    listRepricerPolicies(requestParameters: ListRepricerPoliciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for listRepricerRecommendations without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [q] 
     * @param {string} [status] 
     * @param {Array<string>} [productIds] 
     * @param {Array<string>} [policyIds] 
     * @param {Array<string>} [priceBookIds] 
     * @param {Array<string>} [currencies] 
     * @param {string} [movement] 
     * @param {number} [movePercentMin] 
     * @param {number} [movePercentMax] 
     * @param {string} [amountField] 
     * @param {number} [amountMin] 
     * @param {number} [amountMax] 
     * @param {number} [evidenceMin] 
     * @param {number} [evidenceMax] 
     * @param {Date} [createdFrom] 
     * @param {Date} [createdTo] 
     * @param {Array<string>} [smartFilters] 
     * @param {string} [sort] 
     * @param {string} [direction] 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    listRepricerRecommendationsRequestOpts(requestParameters: ListRepricerRecommendationsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List repricer recommendations
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [q] 
     * @param {string} [status] 
     * @param {Array<string>} [productIds] 
     * @param {Array<string>} [policyIds] 
     * @param {Array<string>} [priceBookIds] 
     * @param {Array<string>} [currencies] 
     * @param {string} [movement] 
     * @param {number} [movePercentMin] 
     * @param {number} [movePercentMax] 
     * @param {string} [amountField] 
     * @param {number} [amountMin] 
     * @param {number} [amountMax] 
     * @param {number} [evidenceMin] 
     * @param {number} [evidenceMax] 
     * @param {Date} [createdFrom] 
     * @param {Date} [createdTo] 
     * @param {Array<string>} [smartFilters] 
     * @param {string} [sort] 
     * @param {string} [direction] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    listRepricerRecommendationsRaw(requestParameters: ListRepricerRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List repricer recommendations
     */
    listRepricerRecommendations(requestParameters: ListRepricerRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for listRepricerRuns without sending the request
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [q] 
     * @param {string} [status] 
     * @param {string} [trigger] 
     * @param {Date} [requestedFrom] 
     * @param {Date} [requestedTo] 
     * @param {string} [outcome] 
     * @param {string} [sort] 
     * @param {string} [direction] 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    listRepricerRunsRequestOpts(requestParameters: ListRepricerRunsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List repricer runs
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [q] 
     * @param {string} [status] 
     * @param {string} [trigger] 
     * @param {Date} [requestedFrom] 
     * @param {Date} [requestedTo] 
     * @param {string} [outcome] 
     * @param {string} [sort] 
     * @param {string} [direction] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    listRepricerRunsRaw(requestParameters: ListRepricerRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List repricer runs
     */
    listRepricerRuns(requestParameters: ListRepricerRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for rollbackRepricerApplication without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} applicationId 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    rollbackRepricerApplicationRequestOpts(requestParameters: RollbackRepricerApplicationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Rollback a repricer application
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} applicationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    rollbackRepricerApplicationRaw(requestParameters: RollbackRepricerApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Rollback a repricer application
     */
    rollbackRepricerApplication(requestParameters: RollbackRepricerApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for updateRepricerPolicy without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} policyId 
     * @param {CreateRepricerPolicyRequest} createRepricerPolicyRequest 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    updateRepricerPolicyRequestOpts(requestParameters: UpdateRepricerPolicyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update a repricer policy
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} policyId 
     * @param {CreateRepricerPolicyRequest} createRepricerPolicyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    updateRepricerPolicyRaw(requestParameters: UpdateRepricerPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Update a repricer policy
     */
    updateRepricerPolicy(requestParameters: UpdateRepricerPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for updateRepricerSettings without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {UpdateRepricerSettingsRequest} updateRepricerSettingsRequest 
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    updateRepricerSettingsRequestOpts(requestParameters: UpdateRepricerSettingsOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update repricer settings
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {UpdateRepricerSettingsRequest} updateRepricerSettingsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepricingApiInterface
     */
    updateRepricerSettingsRaw(requestParameters: UpdateRepricerSettingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Update repricer settings
     */
    updateRepricerSettings(requestParameters: UpdateRepricerSettingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

}

/**
 * 
 */
export class RepricingApi extends runtime.BaseAPI implements RepricingApiInterface {

    /**
     * Creates request options for applyRepricerRecommendation without sending the request
     */
    async applyRepricerRecommendationRequestOpts(requestParameters: ApplyRepricerRecommendationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling applyRepricerRecommendation().'
            );
        }

        if (requestParameters['recommendationId'] == null) {
            throw new runtime.RequiredError(
                'recommendationId',
                'Required parameter "recommendationId" was null or undefined when calling applyRepricerRecommendation().'
            );
        }

        if (requestParameters['applyRepricerRecommendationRequest'] == null) {
            throw new runtime.RequiredError(
                'applyRepricerRecommendationRequest',
                'Required parameter "applyRepricerRecommendationRequest" was null or undefined when calling applyRepricerRecommendation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:apply"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/recommendations/{recommendation_id}/apply`;
        urlPath = urlPath.replace('{recommendation_id}', encodeURIComponent(String(requestParameters['recommendationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplyRepricerRecommendationRequestToJSON(requestParameters['applyRepricerRecommendationRequest']),
        };
    }

    /**
     * Apply a repricer recommendation
     */
    async applyRepricerRecommendationRaw(requestParameters: ApplyRepricerRecommendationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.applyRepricerRecommendationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Apply a repricer recommendation
     */
    async applyRepricerRecommendation(requestParameters: ApplyRepricerRecommendationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.applyRepricerRecommendationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createRepricerExclusion without sending the request
     */
    async createRepricerExclusionRequestOpts(requestParameters: CreateRepricerExclusionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createRepricerExclusion().'
            );
        }

        if (requestParameters['createRepricerExclusionRequest'] == null) {
            throw new runtime.RequiredError(
                'createRepricerExclusionRequest',
                'Required parameter "createRepricerExclusionRequest" was null or undefined when calling createRepricerExclusion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/exclusions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRepricerExclusionRequestToJSON(requestParameters['createRepricerExclusionRequest']),
        };
    }

    /**
     * Create a repricer exclusion
     */
    async createRepricerExclusionRaw(requestParameters: CreateRepricerExclusionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.createRepricerExclusionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create a repricer exclusion
     */
    async createRepricerExclusion(requestParameters: CreateRepricerExclusionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.createRepricerExclusionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createRepricerPolicy without sending the request
     */
    async createRepricerPolicyRequestOpts(requestParameters: CreateRepricerPolicyOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createRepricerPolicy().'
            );
        }

        if (requestParameters['createRepricerPolicyRequest'] == null) {
            throw new runtime.RequiredError(
                'createRepricerPolicyRequest',
                'Required parameter "createRepricerPolicyRequest" was null or undefined when calling createRepricerPolicy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/policies`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRepricerPolicyRequestToJSON(requestParameters['createRepricerPolicyRequest']),
        };
    }

    /**
     * Create a repricer policy
     */
    async createRepricerPolicyRaw(requestParameters: CreateRepricerPolicyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.createRepricerPolicyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create a repricer policy
     */
    async createRepricerPolicy(requestParameters: CreateRepricerPolicyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.createRepricerPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createRepricerRun without sending the request
     */
    async createRepricerRunRequestOpts(requestParameters: CreateRepricerRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createRepricerRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/runs`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Create a repricer run
     */
    async createRepricerRunRaw(requestParameters: CreateRepricerRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptedEnvelope>> {
        const requestOptions = await this.createRepricerRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AcceptedEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create a repricer run
     */
    async createRepricerRun(requestParameters: CreateRepricerRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptedEnvelope> {
        const response = await this.createRepricerRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteRepricerExclusion without sending the request
     */
    async deleteRepricerExclusionRequestOpts(requestParameters: DeleteRepricerExclusionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling deleteRepricerExclusion().'
            );
        }

        if (requestParameters['exclusionId'] == null) {
            throw new runtime.RequiredError(
                'exclusionId',
                'Required parameter "exclusionId" was null or undefined when calling deleteRepricerExclusion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/exclusions/{exclusion_id}`;
        urlPath = urlPath.replace('{exclusion_id}', encodeURIComponent(String(requestParameters['exclusionId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a repricer exclusion
     */
    async deleteRepricerExclusionRaw(requestParameters: DeleteRepricerExclusionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.deleteRepricerExclusionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete a repricer exclusion
     */
    async deleteRepricerExclusion(requestParameters: DeleteRepricerExclusionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.deleteRepricerExclusionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteRepricerPolicy without sending the request
     */
    async deleteRepricerPolicyRequestOpts(requestParameters: DeleteRepricerPolicyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling deleteRepricerPolicy().'
            );
        }

        if (requestParameters['policyId'] == null) {
            throw new runtime.RequiredError(
                'policyId',
                'Required parameter "policyId" was null or undefined when calling deleteRepricerPolicy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/policies/{policy_id}`;
        urlPath = urlPath.replace('{policy_id}', encodeURIComponent(String(requestParameters['policyId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a repricer policy
     */
    async deleteRepricerPolicyRaw(requestParameters: DeleteRepricerPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.deleteRepricerPolicyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete a repricer policy
     */
    async deleteRepricerPolicy(requestParameters: DeleteRepricerPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.deleteRepricerPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRepricerAnalytics without sending the request
     */
    async getRepricerAnalyticsRequestOpts(requestParameters: GetRepricerAnalyticsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling getRepricerAnalytics().'
            );
        }

        if (requestParameters['period'] == null) {
            throw new runtime.RequiredError(
                'period',
                'Required parameter "period" was null or undefined when calling getRepricerAnalytics().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['period'] != null) {
            queryParameters['period'] = requestParameters['period'];
        }

        if (requestParameters['policyId'] != null) {
            queryParameters['policyId'] = requestParameters['policyId'];
        }

        if (requestParameters['priceBookId'] != null) {
            queryParameters['priceBookId'] = requestParameters['priceBookId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/analytics`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get repricer analytics
     */
    async getRepricerAnalyticsRaw(requestParameters: GetRepricerAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getRepricerAnalyticsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get repricer analytics
     */
    async getRepricerAnalytics(requestParameters: GetRepricerAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getRepricerAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRepricerSettings without sending the request
     */
    async getRepricerSettingsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/settings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get repricer settings
     */
    async getRepricerSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getRepricerSettingsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get repricer settings
     */
    async getRepricerSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getRepricerSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRepricerApplications without sending the request
     */
    async listRepricerApplicationsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/applications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List repricer applications
     */
    async listRepricerApplicationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listRepricerApplicationsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List repricer applications
     */
    async listRepricerApplications(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listRepricerApplicationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRepricerExclusions without sending the request
     */
    async listRepricerExclusionsRequestOpts(requestParameters: ListRepricerExclusionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['enabled'] != null) {
            queryParameters['enabled'] = requestParameters['enabled'];
        }

        if (requestParameters['scopeType'] != null) {
            queryParameters['scopeType'] = requestParameters['scopeType'];
        }

        if (requestParameters['scopeTargetIds'] != null) {
            queryParameters['scopeTargetIds'] = requestParameters['scopeTargetIds'];
        }

        if (requestParameters['expiryState'] != null) {
            queryParameters['expiryState'] = requestParameters['expiryState'];
        }

        if (requestParameters['createdFrom'] != null) {
            queryParameters['createdFrom'] = (requestParameters['createdFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['createdTo'] != null) {
            queryParameters['createdTo'] = (requestParameters['createdTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/exclusions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List repricer exclusions
     */
    async listRepricerExclusionsRaw(requestParameters: ListRepricerExclusionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listRepricerExclusionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List repricer exclusions
     */
    async listRepricerExclusions(requestParameters: ListRepricerExclusionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listRepricerExclusionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRepricerPolicies without sending the request
     */
    async listRepricerPoliciesRequestOpts(requestParameters: ListRepricerPoliciesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['enabled'] != null) {
            queryParameters['enabled'] = requestParameters['enabled'];
        }

        if (requestParameters['strategies'] != null) {
            queryParameters['strategies'] = requestParameters['strategies'];
        }

        if (requestParameters['scopeType'] != null) {
            queryParameters['scopeType'] = requestParameters['scopeType'];
        }

        if (requestParameters['scopeTargetIds'] != null) {
            queryParameters['scopeTargetIds'] = requestParameters['scopeTargetIds'];
        }

        if (requestParameters['priorityMin'] != null) {
            queryParameters['priorityMin'] = requestParameters['priorityMin'];
        }

        if (requestParameters['priorityMax'] != null) {
            queryParameters['priorityMax'] = requestParameters['priorityMax'];
        }

        if (requestParameters['guardrailState'] != null) {
            queryParameters['guardrailState'] = requestParameters['guardrailState'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/policies`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List repricer policies
     */
    async listRepricerPoliciesRaw(requestParameters: ListRepricerPoliciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listRepricerPoliciesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List repricer policies
     */
    async listRepricerPolicies(requestParameters: ListRepricerPoliciesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listRepricerPoliciesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRepricerRecommendations without sending the request
     */
    async listRepricerRecommendationsRequestOpts(requestParameters: ListRepricerRecommendationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['productIds'] != null) {
            queryParameters['productIds'] = requestParameters['productIds'];
        }

        if (requestParameters['policyIds'] != null) {
            queryParameters['policyIds'] = requestParameters['policyIds'];
        }

        if (requestParameters['priceBookIds'] != null) {
            queryParameters['priceBookIds'] = requestParameters['priceBookIds'];
        }

        if (requestParameters['currencies'] != null) {
            queryParameters['currencies'] = requestParameters['currencies'];
        }

        if (requestParameters['movement'] != null) {
            queryParameters['movement'] = requestParameters['movement'];
        }

        if (requestParameters['movePercentMin'] != null) {
            queryParameters['movePercentMin'] = requestParameters['movePercentMin'];
        }

        if (requestParameters['movePercentMax'] != null) {
            queryParameters['movePercentMax'] = requestParameters['movePercentMax'];
        }

        if (requestParameters['amountField'] != null) {
            queryParameters['amountField'] = requestParameters['amountField'];
        }

        if (requestParameters['amountMin'] != null) {
            queryParameters['amountMin'] = requestParameters['amountMin'];
        }

        if (requestParameters['amountMax'] != null) {
            queryParameters['amountMax'] = requestParameters['amountMax'];
        }

        if (requestParameters['evidenceMin'] != null) {
            queryParameters['evidenceMin'] = requestParameters['evidenceMin'];
        }

        if (requestParameters['evidenceMax'] != null) {
            queryParameters['evidenceMax'] = requestParameters['evidenceMax'];
        }

        if (requestParameters['createdFrom'] != null) {
            queryParameters['createdFrom'] = (requestParameters['createdFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['createdTo'] != null) {
            queryParameters['createdTo'] = (requestParameters['createdTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['smartFilters'] != null) {
            queryParameters['smartFilters'] = requestParameters['smartFilters'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/recommendations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List repricer recommendations
     */
    async listRepricerRecommendationsRaw(requestParameters: ListRepricerRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listRepricerRecommendationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List repricer recommendations
     */
    async listRepricerRecommendations(requestParameters: ListRepricerRecommendationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listRepricerRecommendationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRepricerRuns without sending the request
     */
    async listRepricerRunsRequestOpts(requestParameters: ListRepricerRunsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['trigger'] != null) {
            queryParameters['trigger'] = requestParameters['trigger'];
        }

        if (requestParameters['requestedFrom'] != null) {
            queryParameters['requestedFrom'] = (requestParameters['requestedFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['requestedTo'] != null) {
            queryParameters['requestedTo'] = (requestParameters['requestedTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['outcome'] != null) {
            queryParameters['outcome'] = requestParameters['outcome'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/runs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List repricer runs
     */
    async listRepricerRunsRaw(requestParameters: ListRepricerRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listRepricerRunsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List repricer runs
     */
    async listRepricerRuns(requestParameters: ListRepricerRunsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listRepricerRunsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rollbackRepricerApplication without sending the request
     */
    async rollbackRepricerApplicationRequestOpts(requestParameters: RollbackRepricerApplicationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling rollbackRepricerApplication().'
            );
        }

        if (requestParameters['applicationId'] == null) {
            throw new runtime.RequiredError(
                'applicationId',
                'Required parameter "applicationId" was null or undefined when calling rollbackRepricerApplication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:apply"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/applications/{application_id}/rollback`;
        urlPath = urlPath.replace('{application_id}', encodeURIComponent(String(requestParameters['applicationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Rollback a repricer application
     */
    async rollbackRepricerApplicationRaw(requestParameters: RollbackRepricerApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.rollbackRepricerApplicationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Rollback a repricer application
     */
    async rollbackRepricerApplication(requestParameters: RollbackRepricerApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.rollbackRepricerApplicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateRepricerPolicy without sending the request
     */
    async updateRepricerPolicyRequestOpts(requestParameters: UpdateRepricerPolicyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateRepricerPolicy().'
            );
        }

        if (requestParameters['policyId'] == null) {
            throw new runtime.RequiredError(
                'policyId',
                'Required parameter "policyId" was null or undefined when calling updateRepricerPolicy().'
            );
        }

        if (requestParameters['createRepricerPolicyRequest'] == null) {
            throw new runtime.RequiredError(
                'createRepricerPolicyRequest',
                'Required parameter "createRepricerPolicyRequest" was null or undefined when calling updateRepricerPolicy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/policies/{policy_id}`;
        urlPath = urlPath.replace('{policy_id}', encodeURIComponent(String(requestParameters['policyId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRepricerPolicyRequestToJSON(requestParameters['createRepricerPolicyRequest']),
        };
    }

    /**
     * Update a repricer policy
     */
    async updateRepricerPolicyRaw(requestParameters: UpdateRepricerPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.updateRepricerPolicyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Update a repricer policy
     */
    async updateRepricerPolicy(requestParameters: UpdateRepricerPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.updateRepricerPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateRepricerSettings without sending the request
     */
    async updateRepricerSettingsRequestOpts(requestParameters: UpdateRepricerSettingsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateRepricerSettings().'
            );
        }

        if (requestParameters['updateRepricerSettingsRequest'] == null) {
            throw new runtime.RequiredError(
                'updateRepricerSettingsRequest',
                'Required parameter "updateRepricerSettingsRequest" was null or undefined when calling updateRepricerSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["repricing:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/repricer/settings`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRepricerSettingsRequestToJSON(requestParameters['updateRepricerSettingsRequest']),
        };
    }

    /**
     * Update repricer settings
     */
    async updateRepricerSettingsRaw(requestParameters: UpdateRepricerSettingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.updateRepricerSettingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Update repricer settings
     */
    async updateRepricerSettings(requestParameters: UpdateRepricerSettingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.updateRepricerSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
