/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AcceptedEnvelope,
    AcceptedEnvelopeFromJSON,
    AcceptedEnvelopeToJSON,
} from '../models/AcceptedEnvelope';
import {
    type CreateWebhookEndpointRequest,
    CreateWebhookEndpointRequestFromJSON,
    CreateWebhookEndpointRequestToJSON,
} from '../models/CreateWebhookEndpointRequest';
import {
    type DataEnvelope,
    DataEnvelopeFromJSON,
    DataEnvelopeToJSON,
} from '../models/DataEnvelope';
import {
    type ListEnvelope,
    ListEnvelopeFromJSON,
    ListEnvelopeToJSON,
} from '../models/ListEnvelope';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface CreateWebhookEndpointOperationRequest {
    idempotencyKey: string;
    createWebhookEndpointRequest: CreateWebhookEndpointRequest;
}

export interface DeleteWebhookEndpointRequest {
    idempotencyKey: string;
    endpointId: string;
}

export interface GetWebhookDeliveryRequest {
    deliveryId: string;
}

export interface GetWebhookEndpointRequest {
    endpointId: string;
}

export interface ListWebhookDeliveriesRequest {
    endpointId?: string;
}

export interface ReplayWebhookDeliveryRequest {
    idempotencyKey: string;
    deliveryId: string;
}

export interface RotateWebhookSigningSecretRequest {
    idempotencyKey: string;
    endpointId: string;
}

export interface TestWebhookEndpointRequest {
    idempotencyKey: string;
    endpointId: string;
}

export interface UpdateWebhookEndpointRequest {
    idempotencyKey: string;
    endpointId: string;
    createWebhookEndpointRequest: CreateWebhookEndpointRequest;
}

/**
 * WebhooksApi - interface
 * 
 * @export
 * @interface WebhooksApiInterface
 */
export interface WebhooksApiInterface {
    /**
     * Creates request options for createWebhookEndpoint without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateWebhookEndpointRequest} createWebhookEndpointRequest 
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    createWebhookEndpointRequestOpts(requestParameters: CreateWebhookEndpointOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a webhook endpoint
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {CreateWebhookEndpointRequest} createWebhookEndpointRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    createWebhookEndpointRaw(requestParameters: CreateWebhookEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Create a webhook endpoint
     */
    createWebhookEndpoint(requestParameters: CreateWebhookEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for deleteWebhookEndpoint without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} endpointId 
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    deleteWebhookEndpointRequestOpts(requestParameters: DeleteWebhookEndpointRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Delete a webhook endpoint
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} endpointId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    deleteWebhookEndpointRaw(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Delete a webhook endpoint
     */
    deleteWebhookEndpoint(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getWebhookDelivery without sending the request
     * @param {string} deliveryId 
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    getWebhookDeliveryRequestOpts(requestParameters: GetWebhookDeliveryRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a webhook delivery
     * @param {string} deliveryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    getWebhookDeliveryRaw(requestParameters: GetWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get a webhook delivery
     */
    getWebhookDelivery(requestParameters: GetWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for getWebhookEndpoint without sending the request
     * @param {string} endpointId 
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    getWebhookEndpointRequestOpts(requestParameters: GetWebhookEndpointRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a webhook endpoint
     * @param {string} endpointId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    getWebhookEndpointRaw(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Get a webhook endpoint
     */
    getWebhookEndpoint(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for listWebhookDeliveries without sending the request
     * @param {string} [endpointId] 
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    listWebhookDeliveriesRequestOpts(requestParameters: ListWebhookDeliveriesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List webhook deliveries
     * @param {string} [endpointId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    listWebhookDeliveriesRaw(requestParameters: ListWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List webhook deliveries
     */
    listWebhookDeliveries(requestParameters: ListWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for listWebhookEndpoints without sending the request
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    listWebhookEndpointsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List webhook endpoints
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    listWebhookEndpointsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>>;

    /**
     * List webhook endpoints
     */
    listWebhookEndpoints(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope>;

    /**
     * Creates request options for replayWebhookDelivery without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} deliveryId 
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    replayWebhookDeliveryRequestOpts(requestParameters: ReplayWebhookDeliveryRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Replay a webhook delivery
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} deliveryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    replayWebhookDeliveryRaw(requestParameters: ReplayWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptedEnvelope>>;

    /**
     * Replay a webhook delivery
     */
    replayWebhookDelivery(requestParameters: ReplayWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptedEnvelope>;

    /**
     * Creates request options for rotateWebhookSigningSecret without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} endpointId 
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    rotateWebhookSigningSecretRequestOpts(requestParameters: RotateWebhookSigningSecretRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Rotate a webhook signing secret
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} endpointId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    rotateWebhookSigningSecretRaw(requestParameters: RotateWebhookSigningSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Rotate a webhook signing secret
     */
    rotateWebhookSigningSecret(requestParameters: RotateWebhookSigningSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

    /**
     * Creates request options for testWebhookEndpoint without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} endpointId 
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    testWebhookEndpointRequestOpts(requestParameters: TestWebhookEndpointRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Send a signed test event
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} endpointId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    testWebhookEndpointRaw(requestParameters: TestWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptedEnvelope>>;

    /**
     * Send a signed test event
     */
    testWebhookEndpoint(requestParameters: TestWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptedEnvelope>;

    /**
     * Creates request options for updateWebhookEndpoint without sending the request
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} endpointId 
     * @param {CreateWebhookEndpointRequest} createWebhookEndpointRequest 
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    updateWebhookEndpointRequestOpts(requestParameters: UpdateWebhookEndpointRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update a webhook endpoint
     * @param {string} idempotencyKey Unique key retained for 24 hours. Reusing a key with another payload returns 409.
     * @param {string} endpointId 
     * @param {CreateWebhookEndpointRequest} createWebhookEndpointRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    updateWebhookEndpointRaw(requestParameters: UpdateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>>;

    /**
     * Update a webhook endpoint
     */
    updateWebhookEndpoint(requestParameters: UpdateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope>;

}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI implements WebhooksApiInterface {

    /**
     * Creates request options for createWebhookEndpoint without sending the request
     */
    async createWebhookEndpointRequestOpts(requestParameters: CreateWebhookEndpointOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createWebhookEndpoint().'
            );
        }

        if (requestParameters['createWebhookEndpointRequest'] == null) {
            throw new runtime.RequiredError(
                'createWebhookEndpointRequest',
                'Required parameter "createWebhookEndpointRequest" was null or undefined when calling createWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["webhooks:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webhook-endpoints`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebhookEndpointRequestToJSON(requestParameters['createWebhookEndpointRequest']),
        };
    }

    /**
     * Create a webhook endpoint
     */
    async createWebhookEndpointRaw(requestParameters: CreateWebhookEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.createWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create a webhook endpoint
     */
    async createWebhookEndpoint(requestParameters: CreateWebhookEndpointOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.createWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteWebhookEndpoint without sending the request
     */
    async deleteWebhookEndpointRequestOpts(requestParameters: DeleteWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling deleteWebhookEndpoint().'
            );
        }

        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling deleteWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["webhooks:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webhook-endpoints/{endpoint_id}`;
        urlPath = urlPath.replace('{endpoint_id}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a webhook endpoint
     */
    async deleteWebhookEndpointRaw(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.deleteWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete a webhook endpoint
     */
    async deleteWebhookEndpoint(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.deleteWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWebhookDelivery without sending the request
     */
    async getWebhookDeliveryRequestOpts(requestParameters: GetWebhookDeliveryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deliveryId'] == null) {
            throw new runtime.RequiredError(
                'deliveryId',
                'Required parameter "deliveryId" was null or undefined when calling getWebhookDelivery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["webhooks:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webhook-deliveries/{delivery_id}`;
        urlPath = urlPath.replace('{delivery_id}', encodeURIComponent(String(requestParameters['deliveryId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a webhook delivery
     */
    async getWebhookDeliveryRaw(requestParameters: GetWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getWebhookDeliveryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get a webhook delivery
     */
    async getWebhookDelivery(requestParameters: GetWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getWebhookDeliveryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWebhookEndpoint without sending the request
     */
    async getWebhookEndpointRequestOpts(requestParameters: GetWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling getWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["webhooks:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webhook-endpoints/{endpoint_id}`;
        urlPath = urlPath.replace('{endpoint_id}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a webhook endpoint
     */
    async getWebhookEndpointRaw(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.getWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Get a webhook endpoint
     */
    async getWebhookEndpoint(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.getWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookDeliveries without sending the request
     */
    async listWebhookDeliveriesRequestOpts(requestParameters: ListWebhookDeliveriesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['endpointId'] != null) {
            queryParameters['endpointId'] = requestParameters['endpointId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["webhooks:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webhook-deliveries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List webhook deliveries
     */
    async listWebhookDeliveriesRaw(requestParameters: ListWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listWebhookDeliveriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List webhook deliveries
     */
    async listWebhookDeliveries(requestParameters: ListWebhookDeliveriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listWebhookDeliveriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookEndpoints without sending the request
     */
    async listWebhookEndpointsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["webhooks:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webhook-endpoints`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List webhook endpoints
     */
    async listWebhookEndpointsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEnvelope>> {
        const requestOptions = await this.listWebhookEndpointsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List webhook endpoints
     */
    async listWebhookEndpoints(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEnvelope> {
        const response = await this.listWebhookEndpointsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for replayWebhookDelivery without sending the request
     */
    async replayWebhookDeliveryRequestOpts(requestParameters: ReplayWebhookDeliveryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling replayWebhookDelivery().'
            );
        }

        if (requestParameters['deliveryId'] == null) {
            throw new runtime.RequiredError(
                'deliveryId',
                'Required parameter "deliveryId" was null or undefined when calling replayWebhookDelivery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["webhooks:replay"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webhook-deliveries/{delivery_id}/replay`;
        urlPath = urlPath.replace('{delivery_id}', encodeURIComponent(String(requestParameters['deliveryId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Replay a webhook delivery
     */
    async replayWebhookDeliveryRaw(requestParameters: ReplayWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptedEnvelope>> {
        const requestOptions = await this.replayWebhookDeliveryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AcceptedEnvelopeFromJSON(jsonValue));
    }

    /**
     * Replay a webhook delivery
     */
    async replayWebhookDelivery(requestParameters: ReplayWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptedEnvelope> {
        const response = await this.replayWebhookDeliveryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rotateWebhookSigningSecret without sending the request
     */
    async rotateWebhookSigningSecretRequestOpts(requestParameters: RotateWebhookSigningSecretRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling rotateWebhookSigningSecret().'
            );
        }

        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling rotateWebhookSigningSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["webhooks:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webhook-endpoints/{endpoint_id}/rotate-secret`;
        urlPath = urlPath.replace('{endpoint_id}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Rotate a webhook signing secret
     */
    async rotateWebhookSigningSecretRaw(requestParameters: RotateWebhookSigningSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.rotateWebhookSigningSecretRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Rotate a webhook signing secret
     */
    async rotateWebhookSigningSecret(requestParameters: RotateWebhookSigningSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.rotateWebhookSigningSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for testWebhookEndpoint without sending the request
     */
    async testWebhookEndpointRequestOpts(requestParameters: TestWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling testWebhookEndpoint().'
            );
        }

        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling testWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["webhooks:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webhook-endpoints/{endpoint_id}/test`;
        urlPath = urlPath.replace('{endpoint_id}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Send a signed test event
     */
    async testWebhookEndpointRaw(requestParameters: TestWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptedEnvelope>> {
        const requestOptions = await this.testWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AcceptedEnvelopeFromJSON(jsonValue));
    }

    /**
     * Send a signed test event
     */
    async testWebhookEndpoint(requestParameters: TestWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptedEnvelope> {
        const response = await this.testWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateWebhookEndpoint without sending the request
     */
    async updateWebhookEndpointRequestOpts(requestParameters: UpdateWebhookEndpointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateWebhookEndpoint().'
            );
        }

        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling updateWebhookEndpoint().'
            );
        }

        if (requestParameters['createWebhookEndpointRequest'] == null) {
            throw new runtime.RequiredError(
                'createWebhookEndpointRequest',
                'Required parameter "createWebhookEndpointRequest" was null or undefined when calling updateWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("RivalikaApiKey", ["webhooks:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webhook-endpoints/{endpoint_id}`;
        urlPath = urlPath.replace('{endpoint_id}', encodeURIComponent(String(requestParameters['endpointId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebhookEndpointRequestToJSON(requestParameters['createWebhookEndpointRequest']),
        };
    }

    /**
     * Update a webhook endpoint
     */
    async updateWebhookEndpointRaw(requestParameters: UpdateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataEnvelope>> {
        const requestOptions = await this.updateWebhookEndpointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataEnvelopeFromJSON(jsonValue));
    }

    /**
     * Update a webhook endpoint
     */
    async updateWebhookEndpoint(requestParameters: UpdateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataEnvelope> {
        const response = await this.updateWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
