/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AcceptedEnvelopeData } from './AcceptedEnvelopeData';
import {
    AcceptedEnvelopeDataFromJSON,
    AcceptedEnvelopeDataFromJSONTyped,
    AcceptedEnvelopeDataToJSON,
    AcceptedEnvelopeDataToJSONTyped,
} from './AcceptedEnvelopeData';

/**
 * 
 * @export
 * @interface AcceptedEnvelope
 */
export interface AcceptedEnvelope {
    /**
     * 
     * @type {AcceptedEnvelopeData}
     * @memberof AcceptedEnvelope
     */
    data: AcceptedEnvelopeData;
}

/**
 * Check if a given object implements the AcceptedEnvelope interface.
 */
export function instanceOfAcceptedEnvelope(value: object): value is AcceptedEnvelope {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AcceptedEnvelopeFromJSON(json: any): AcceptedEnvelope {
    return AcceptedEnvelopeFromJSONTyped(json, false);
}

export function AcceptedEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptedEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AcceptedEnvelopeDataFromJSON(json['data']),
    };
}

export function AcceptedEnvelopeToJSON(json: any): AcceptedEnvelope {
    return AcceptedEnvelopeToJSONTyped(json, false);
}

export function AcceptedEnvelopeToJSONTyped(value?: AcceptedEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AcceptedEnvelopeDataToJSON(value['data']),
    };
}

