/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcceptedEnvelopeData
 */
export interface AcceptedEnvelopeData {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof AcceptedEnvelopeData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AcceptedEnvelopeData
     */
    status: string;
}

/**
 * Check if a given object implements the AcceptedEnvelopeData interface.
 */
export function instanceOfAcceptedEnvelopeData(value: object): value is AcceptedEnvelopeData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AcceptedEnvelopeDataFromJSON(json: any): AcceptedEnvelopeData {
    return AcceptedEnvelopeDataFromJSONTyped(json, false);
}

export function AcceptedEnvelopeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptedEnvelopeData {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'status': json['status'],
    };
}

export function AcceptedEnvelopeDataToJSON(json: any): AcceptedEnvelopeData {
    return AcceptedEnvelopeDataToJSONTyped(json, false);
}

export function AcceptedEnvelopeDataToJSONTyped(value?: AcceptedEnvelopeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'status': value['status'],
    };
}

