/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyRepricerRecommendationRequest
 */
export interface ApplyRepricerRecommendationRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplyRepricerRecommendationRequest
     */
    overrideAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplyRepricerRecommendationRequest
     */
    overrideReason?: string;
}

/**
 * Check if a given object implements the ApplyRepricerRecommendationRequest interface.
 */
export function instanceOfApplyRepricerRecommendationRequest(value: object): value is ApplyRepricerRecommendationRequest {
    return true;
}

export function ApplyRepricerRecommendationRequestFromJSON(json: any): ApplyRepricerRecommendationRequest {
    return ApplyRepricerRecommendationRequestFromJSONTyped(json, false);
}

export function ApplyRepricerRecommendationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyRepricerRecommendationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'overrideAmount': json['overrideAmount'] == null ? undefined : json['overrideAmount'],
        'overrideReason': json['overrideReason'] == null ? undefined : json['overrideReason'],
    };
}

export function ApplyRepricerRecommendationRequestToJSON(json: any): ApplyRepricerRecommendationRequest {
    return ApplyRepricerRecommendationRequestToJSONTyped(json, false);
}

export function ApplyRepricerRecommendationRequestToJSONTyped(value?: ApplyRepricerRecommendationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'overrideAmount': value['overrideAmount'],
        'overrideReason': value['overrideReason'],
    };
}

