/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommercialImportDetailEnvelopeDataRowErrorsInner
 */
export interface CommercialImportDetailEnvelopeDataRowErrorsInner {
    /**
     * 
     * @type {number}
     * @memberof CommercialImportDetailEnvelopeDataRowErrorsInner
     */
    rowNumber: number;
    /**
     * 
     * @type {string}
     * @memberof CommercialImportDetailEnvelopeDataRowErrorsInner
     */
    message: string;
}

/**
 * Check if a given object implements the CommercialImportDetailEnvelopeDataRowErrorsInner interface.
 */
export function instanceOfCommercialImportDetailEnvelopeDataRowErrorsInner(value: object): value is CommercialImportDetailEnvelopeDataRowErrorsInner {
    if (!('rowNumber' in value) || value['rowNumber'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommercialImportDetailEnvelopeDataRowErrorsInnerFromJSON(json: any): CommercialImportDetailEnvelopeDataRowErrorsInner {
    return CommercialImportDetailEnvelopeDataRowErrorsInnerFromJSONTyped(json, false);
}

export function CommercialImportDetailEnvelopeDataRowErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialImportDetailEnvelopeDataRowErrorsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'rowNumber': json['row_number'],
        'message': json['message'],
    };
}

export function CommercialImportDetailEnvelopeDataRowErrorsInnerToJSON(json: any): CommercialImportDetailEnvelopeDataRowErrorsInner {
    return CommercialImportDetailEnvelopeDataRowErrorsInnerToJSONTyped(json, false);
}

export function CommercialImportDetailEnvelopeDataRowErrorsInnerToJSONTyped(value?: CommercialImportDetailEnvelopeDataRowErrorsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row_number': value['rowNumber'],
        'message': value['message'],
    };
}

