/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommercialImportDetailEnvelopeDataRowErrorsInner } from './CommercialImportDetailEnvelopeDataRowErrorsInner';
import {
    CommercialImportDetailEnvelopeDataRowErrorsInnerFromJSON,
    CommercialImportDetailEnvelopeDataRowErrorsInnerFromJSONTyped,
    CommercialImportDetailEnvelopeDataRowErrorsInnerToJSON,
    CommercialImportDetailEnvelopeDataRowErrorsInnerToJSONTyped,
} from './CommercialImportDetailEnvelopeDataRowErrorsInner';

/**
 * 
 * @export
 * @interface CommercialImportDetailEnvelopeData
 */
export interface CommercialImportDetailEnvelopeData {
    /**
     * 
     * @type {string}
     * @memberof CommercialImportDetailEnvelopeData
     */
    id: string;
    /**
     * 
     * @type {CommercialImportDetailEnvelopeDataKindEnum}
     * @memberof CommercialImportDetailEnvelopeData
     */
    kind: CommercialImportDetailEnvelopeDataKindEnum;
    /**
     * 
     * @type {CommercialImportDetailEnvelopeDataStatusEnum}
     * @memberof CommercialImportDetailEnvelopeData
     */
    status: CommercialImportDetailEnvelopeDataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CommercialImportDetailEnvelopeData
     */
    fileName: string;
    /**
     * 
     * @type {boolean}
     * @memberof CommercialImportDetailEnvelopeData
     */
    dryRun: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommercialImportDetailEnvelopeData
     */
    sheetName: string | null;
    /**
     * 
     * @type {number}
     * @memberof CommercialImportDetailEnvelopeData
     */
    totalRows: number;
    /**
     * 
     * @type {number}
     * @memberof CommercialImportDetailEnvelopeData
     */
    importedRows: number;
    /**
     * 
     * @type {number}
     * @memberof CommercialImportDetailEnvelopeData
     */
    rejectedRows: number;
    /**
     * 
     * @type {number}
     * @memberof CommercialImportDetailEnvelopeData
     */
    lastProcessedRow: number;
    /**
     * 
     * @type {boolean}
     * @memberof CommercialImportDetailEnvelopeData
     */
    hasErrorReport: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommercialImportDetailEnvelopeData
     */
    failureSummary: string | null;
    /**
     * 
     * @type {CommercialImportDetailEnvelopeDataErrorCodeEnum}
     * @memberof CommercialImportDetailEnvelopeData
     */
    errorCode: CommercialImportDetailEnvelopeDataErrorCodeEnum | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommercialImportDetailEnvelopeData
     */
    errorParams: { [key: string]: string; };
    /**
     * 
     * @type {Array<CommercialImportDetailEnvelopeDataRowErrorsInner>}
     * @memberof CommercialImportDetailEnvelopeData
     */
    rowErrors: Array<CommercialImportDetailEnvelopeDataRowErrorsInner>;
    /**
     * 
     * @type {boolean}
     * @memberof CommercialImportDetailEnvelopeData
     */
    rowErrorsTruncated: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CommercialImportDetailEnvelopeData
     */
    startedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CommercialImportDetailEnvelopeData
     */
    completedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CommercialImportDetailEnvelopeData
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CommercialImportDetailEnvelopeData
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const CommercialImportDetailEnvelopeDataKindEnum = {
    Products: 'products',
    Partners: 'partners',
    SupplierOffers: 'supplier_offers',
    PriceBooks: 'price_books'
} as const;
export type CommercialImportDetailEnvelopeDataKindEnum = typeof CommercialImportDetailEnvelopeDataKindEnum[keyof typeof CommercialImportDetailEnvelopeDataKindEnum];

/**
 * @export
 */
export const CommercialImportDetailEnvelopeDataStatusEnum = {
    Queued: 'queued',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type CommercialImportDetailEnvelopeDataStatusEnum = typeof CommercialImportDetailEnvelopeDataStatusEnum[keyof typeof CommercialImportDetailEnvelopeDataStatusEnum];

/**
 * @export
 */
export const CommercialImportDetailEnvelopeDataErrorCodeEnum = {
    FileTooLarge: 'file_too_large',
    UnsupportedFileType: 'unsupported_file_type',
    InvalidUtf8: 'invalid_utf8',
    NullBytes: 'null_bytes',
    XlsxArchiveInvalid: 'xlsx_archive_invalid',
    XlsxExpansion: 'xlsx_expansion',
    FormulasNotAllowed: 'formulas_not_allowed',
    WorksheetUnavailable: 'worksheet_unavailable',
    RowLimit: 'row_limit',
    ColumnLimit: 'column_limit',
    NoHeaders: 'no_headers',
    DuplicateColumns: 'duplicate_columns',
    UnsupportedColumns: 'unsupported_columns',
    MissingRequiredColumns: 'missing_required_columns',
    MappedSourceMissing: 'mapped_source_missing',
    UnsupportedTargetColumn: 'unsupported_target_column',
    SizeMismatch: 'size_mismatch',
    ShaMismatch: 'sha_mismatch',
    LegacyIdentityUnverified: 'legacy_identity_unverified',
    StorageReferenceInvalid: 'storage_reference_invalid',
    RuntimeUnavailable: 'runtime_unavailable',
    Unknown: 'unknown'
} as const;
export type CommercialImportDetailEnvelopeDataErrorCodeEnum = typeof CommercialImportDetailEnvelopeDataErrorCodeEnum[keyof typeof CommercialImportDetailEnvelopeDataErrorCodeEnum];


/**
 * Check if a given object implements the CommercialImportDetailEnvelopeData interface.
 */
export function instanceOfCommercialImportDetailEnvelopeData(value: object): value is CommercialImportDetailEnvelopeData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('dryRun' in value) || value['dryRun'] === undefined) return false;
    if (!('sheetName' in value) || value['sheetName'] === undefined) return false;
    if (!('totalRows' in value) || value['totalRows'] === undefined) return false;
    if (!('importedRows' in value) || value['importedRows'] === undefined) return false;
    if (!('rejectedRows' in value) || value['rejectedRows'] === undefined) return false;
    if (!('lastProcessedRow' in value) || value['lastProcessedRow'] === undefined) return false;
    if (!('hasErrorReport' in value) || value['hasErrorReport'] === undefined) return false;
    if (!('failureSummary' in value) || value['failureSummary'] === undefined) return false;
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('errorParams' in value) || value['errorParams'] === undefined) return false;
    if (!('rowErrors' in value) || value['rowErrors'] === undefined) return false;
    if (!('rowErrorsTruncated' in value) || value['rowErrorsTruncated'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CommercialImportDetailEnvelopeDataFromJSON(json: any): CommercialImportDetailEnvelopeData {
    return CommercialImportDetailEnvelopeDataFromJSONTyped(json, false);
}

export function CommercialImportDetailEnvelopeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialImportDetailEnvelopeData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kind': json['kind'],
        'status': json['status'],
        'fileName': json['file_name'],
        'dryRun': json['dry_run'],
        'sheetName': json['sheet_name'],
        'totalRows': json['total_rows'],
        'importedRows': json['imported_rows'],
        'rejectedRows': json['rejected_rows'],
        'lastProcessedRow': json['last_processed_row'],
        'hasErrorReport': json['has_error_report'],
        'failureSummary': json['failure_summary'],
        'errorCode': json['error_code'],
        'errorParams': json['error_params'],
        'rowErrors': ((json['row_errors'] as Array<any>).map(CommercialImportDetailEnvelopeDataRowErrorsInnerFromJSON)),
        'rowErrorsTruncated': json['row_errors_truncated'],
        'startedAt': (json['started_at'] == null ? null : new Date(json['started_at'])),
        'completedAt': (json['completed_at'] == null ? null : new Date(json['completed_at'])),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function CommercialImportDetailEnvelopeDataToJSON(json: any): CommercialImportDetailEnvelopeData {
    return CommercialImportDetailEnvelopeDataToJSONTyped(json, false);
}

export function CommercialImportDetailEnvelopeDataToJSONTyped(value?: CommercialImportDetailEnvelopeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': value['kind'],
        'status': value['status'],
        'file_name': value['fileName'],
        'dry_run': value['dryRun'],
        'sheet_name': value['sheetName'],
        'total_rows': value['totalRows'],
        'imported_rows': value['importedRows'],
        'rejected_rows': value['rejectedRows'],
        'last_processed_row': value['lastProcessedRow'],
        'has_error_report': value['hasErrorReport'],
        'failure_summary': value['failureSummary'],
        'error_code': value['errorCode'],
        'error_params': value['errorParams'],
        'row_errors': ((value['rowErrors'] as Array<any>).map(CommercialImportDetailEnvelopeDataRowErrorsInnerToJSON)),
        'row_errors_truncated': value['rowErrorsTruncated'],
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

