/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommercialProductLifecycleEnvelopeData
 */
export interface CommercialProductLifecycleEnvelopeData {
    /**
     * 
     * @type {string}
     * @memberof CommercialProductLifecycleEnvelopeData
     */
    productId: string;
    /**
     * 
     * @type {CommercialProductLifecycleEnvelopeDataStatusEnum}
     * @memberof CommercialProductLifecycleEnvelopeData
     */
    status: CommercialProductLifecycleEnvelopeDataStatusEnum;
}


/**
 * @export
 */
export const CommercialProductLifecycleEnvelopeDataStatusEnum = {
    Active: 'active',
    Archived: 'archived'
} as const;
export type CommercialProductLifecycleEnvelopeDataStatusEnum = typeof CommercialProductLifecycleEnvelopeDataStatusEnum[keyof typeof CommercialProductLifecycleEnvelopeDataStatusEnum];


/**
 * Check if a given object implements the CommercialProductLifecycleEnvelopeData interface.
 */
export function instanceOfCommercialProductLifecycleEnvelopeData(value: object): value is CommercialProductLifecycleEnvelopeData {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CommercialProductLifecycleEnvelopeDataFromJSON(json: any): CommercialProductLifecycleEnvelopeData {
    return CommercialProductLifecycleEnvelopeDataFromJSONTyped(json, false);
}

export function CommercialProductLifecycleEnvelopeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialProductLifecycleEnvelopeData {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['product_id'],
        'status': json['status'],
    };
}

export function CommercialProductLifecycleEnvelopeDataToJSON(json: any): CommercialProductLifecycleEnvelopeData {
    return CommercialProductLifecycleEnvelopeDataToJSONTyped(json, false);
}

export function CommercialProductLifecycleEnvelopeDataToJSONTyped(value?: CommercialProductLifecycleEnvelopeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_id': value['productId'],
        'status': value['status'],
    };
}

