/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommercialImportDetailEnvelopeDataRowErrorsInner
 */
export interface CommercialImportDetailEnvelopeDataRowErrorsInner {
    /**
     * 
     * @type {number}
     * @memberof CommercialImportDetailEnvelopeDataRowErrorsInner
     */
    rowNumber: number;
    /**
     * 
     * @type {string}
     * @memberof CommercialImportDetailEnvelopeDataRowErrorsInner
     */
    message: string;
    /**
     * 
     * @type {CommercialImportDetailEnvelopeDataRowErrorsInnerCodeEnum}
     * @memberof CommercialImportDetailEnvelopeDataRowErrorsInner
     */
    code: CommercialImportDetailEnvelopeDataRowErrorsInnerCodeEnum;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommercialImportDetailEnvelopeDataRowErrorsInner
     */
    params: { [key: string]: string; };
}


/**
 * @export
 */
export const CommercialImportDetailEnvelopeDataRowErrorsInnerCodeEnum = {
    FieldRequired: 'field_required',
    FieldNotInteger: 'field_not_integer',
    FieldNotAmount: 'field_not_amount',
    FieldNotBoolean: 'field_not_boolean',
    FieldNotDate: 'field_not_date',
    CurrencyUnsupported: 'currency_unsupported',
    PriceBookKindInvalid: 'price_book_kind_invalid',
    ProductNotFound: 'product_not_found',
    ParentNotFound: 'parent_not_found',
    PartnerNotFound: 'partner_not_found',
    RolesInvalid: 'roles_invalid',
    AttributesInvalidJson: 'attributes_invalid_json',
    AttributesNotObject: 'attributes_not_object',
    AttributesTooMany: 'attributes_too_many',
    ValidFromAfterValidTo: 'valid_from_after_valid_to',
    VariantCycle: 'variant_cycle',
    SourceOwnedByOther: 'source_owned_by_other',
    SourceIdentityOtherProduct: 'source_identity_other_product',
    SourceIdentityIncomplete: 'source_identity_incomplete',
    TaxBasisInvalid: 'tax_basis_invalid',
    VatRateInvalid: 'vat_rate_invalid',
    Unknown: 'unknown'
} as const;
export type CommercialImportDetailEnvelopeDataRowErrorsInnerCodeEnum = typeof CommercialImportDetailEnvelopeDataRowErrorsInnerCodeEnum[keyof typeof CommercialImportDetailEnvelopeDataRowErrorsInnerCodeEnum];


/**
 * Check if a given object implements the CommercialImportDetailEnvelopeDataRowErrorsInner interface.
 */
export function instanceOfCommercialImportDetailEnvelopeDataRowErrorsInner(value: object): value is CommercialImportDetailEnvelopeDataRowErrorsInner {
    if (!('rowNumber' in value) || value['rowNumber'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    return true;
}

export function CommercialImportDetailEnvelopeDataRowErrorsInnerFromJSON(json: any): CommercialImportDetailEnvelopeDataRowErrorsInner {
    return CommercialImportDetailEnvelopeDataRowErrorsInnerFromJSONTyped(json, false);
}

export function CommercialImportDetailEnvelopeDataRowErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialImportDetailEnvelopeDataRowErrorsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'rowNumber': json['row_number'],
        'message': json['message'],
        'code': json['code'],
        'params': json['params'],
    };
}

export function CommercialImportDetailEnvelopeDataRowErrorsInnerToJSON(json: any): CommercialImportDetailEnvelopeDataRowErrorsInner {
    return CommercialImportDetailEnvelopeDataRowErrorsInnerToJSONTyped(json, false);
}

export function CommercialImportDetailEnvelopeDataRowErrorsInnerToJSONTyped(value?: CommercialImportDetailEnvelopeDataRowErrorsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row_number': value['rowNumber'],
        'message': value['message'],
        'code': value['code'],
        'params': value['params'],
    };
}

