/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommercialImportPreparedUploadEnvelopeData } from './CommercialImportPreparedUploadEnvelopeData';
import {
    CommercialImportPreparedUploadEnvelopeDataFromJSON,
    CommercialImportPreparedUploadEnvelopeDataFromJSONTyped,
    CommercialImportPreparedUploadEnvelopeDataToJSON,
    CommercialImportPreparedUploadEnvelopeDataToJSONTyped,
} from './CommercialImportPreparedUploadEnvelopeData';

/**
 * 
 * @export
 * @interface CommercialImportPreparedUploadEnvelope
 */
export interface CommercialImportPreparedUploadEnvelope {
    /**
     * 
     * @type {CommercialImportPreparedUploadEnvelopeData}
     * @memberof CommercialImportPreparedUploadEnvelope
     */
    data: CommercialImportPreparedUploadEnvelopeData;
}

/**
 * Check if a given object implements the CommercialImportPreparedUploadEnvelope interface.
 */
export function instanceOfCommercialImportPreparedUploadEnvelope(value: object): value is CommercialImportPreparedUploadEnvelope {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CommercialImportPreparedUploadEnvelopeFromJSON(json: any): CommercialImportPreparedUploadEnvelope {
    return CommercialImportPreparedUploadEnvelopeFromJSONTyped(json, false);
}

export function CommercialImportPreparedUploadEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialImportPreparedUploadEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CommercialImportPreparedUploadEnvelopeDataFromJSON(json['data']),
    };
}

export function CommercialImportPreparedUploadEnvelopeToJSON(json: any): CommercialImportPreparedUploadEnvelope {
    return CommercialImportPreparedUploadEnvelopeToJSONTyped(json, false);
}

export function CommercialImportPreparedUploadEnvelopeToJSONTyped(value?: CommercialImportPreparedUploadEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CommercialImportPreparedUploadEnvelopeDataToJSON(value['data']),
    };
}

