/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommercialProductLifecycleEnvelopeData } from './CommercialProductLifecycleEnvelopeData';
import {
    CommercialProductLifecycleEnvelopeDataFromJSON,
    CommercialProductLifecycleEnvelopeDataFromJSONTyped,
    CommercialProductLifecycleEnvelopeDataToJSON,
    CommercialProductLifecycleEnvelopeDataToJSONTyped,
} from './CommercialProductLifecycleEnvelopeData';

/**
 * 
 * @export
 * @interface CommercialProductLifecycleEnvelope
 */
export interface CommercialProductLifecycleEnvelope {
    /**
     * 
     * @type {CommercialProductLifecycleEnvelopeData}
     * @memberof CommercialProductLifecycleEnvelope
     */
    data: CommercialProductLifecycleEnvelopeData;
}

/**
 * Check if a given object implements the CommercialProductLifecycleEnvelope interface.
 */
export function instanceOfCommercialProductLifecycleEnvelope(value: object): value is CommercialProductLifecycleEnvelope {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CommercialProductLifecycleEnvelopeFromJSON(json: any): CommercialProductLifecycleEnvelope {
    return CommercialProductLifecycleEnvelopeFromJSONTyped(json, false);
}

export function CommercialProductLifecycleEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialProductLifecycleEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CommercialProductLifecycleEnvelopeDataFromJSON(json['data']),
    };
}

export function CommercialProductLifecycleEnvelopeToJSON(json: any): CommercialProductLifecycleEnvelope {
    return CommercialProductLifecycleEnvelopeToJSONTyped(json, false);
}

export function CommercialProductLifecycleEnvelopeToJSONTyped(value?: CommercialProductLifecycleEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CommercialProductLifecycleEnvelopeDataToJSON(value['data']),
    };
}

