/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommercialImportPreparedUploadEnvelopeDataUploadHeaders } from './CommercialImportPreparedUploadEnvelopeDataUploadHeaders';
import {
    CommercialImportPreparedUploadEnvelopeDataUploadHeadersFromJSON,
    CommercialImportPreparedUploadEnvelopeDataUploadHeadersFromJSONTyped,
    CommercialImportPreparedUploadEnvelopeDataUploadHeadersToJSON,
    CommercialImportPreparedUploadEnvelopeDataUploadHeadersToJSONTyped,
} from './CommercialImportPreparedUploadEnvelopeDataUploadHeaders';

/**
 * 
 * @export
 * @interface CommercialImportPreparedUploadEnvelopeData
 */
export interface CommercialImportPreparedUploadEnvelopeData {
    /**
     * 
     * @type {string}
     * @memberof CommercialImportPreparedUploadEnvelopeData
     */
    storageKey: string;
    /**
     * 
     * @type {string}
     * @memberof CommercialImportPreparedUploadEnvelopeData
     */
    uploadUrl: string;
    /**
     * 
     * @type {CommercialImportPreparedUploadEnvelopeDataUploadHeaders}
     * @memberof CommercialImportPreparedUploadEnvelopeData
     */
    uploadHeaders: CommercialImportPreparedUploadEnvelopeDataUploadHeaders;
    /**
     * 
     * @type {number}
     * @memberof CommercialImportPreparedUploadEnvelopeData
     */
    expiresInSeconds: number;
}

/**
 * Check if a given object implements the CommercialImportPreparedUploadEnvelopeData interface.
 */
export function instanceOfCommercialImportPreparedUploadEnvelopeData(value: object): value is CommercialImportPreparedUploadEnvelopeData {
    if (!('storageKey' in value) || value['storageKey'] === undefined) return false;
    if (!('uploadUrl' in value) || value['uploadUrl'] === undefined) return false;
    if (!('uploadHeaders' in value) || value['uploadHeaders'] === undefined) return false;
    if (!('expiresInSeconds' in value) || value['expiresInSeconds'] === undefined) return false;
    return true;
}

export function CommercialImportPreparedUploadEnvelopeDataFromJSON(json: any): CommercialImportPreparedUploadEnvelopeData {
    return CommercialImportPreparedUploadEnvelopeDataFromJSONTyped(json, false);
}

export function CommercialImportPreparedUploadEnvelopeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialImportPreparedUploadEnvelopeData {
    if (json == null) {
        return json;
    }
    return {
        
        'storageKey': json['storage_key'],
        'uploadUrl': json['upload_url'],
        'uploadHeaders': CommercialImportPreparedUploadEnvelopeDataUploadHeadersFromJSON(json['upload_headers']),
        'expiresInSeconds': json['expires_in_seconds'],
    };
}

export function CommercialImportPreparedUploadEnvelopeDataToJSON(json: any): CommercialImportPreparedUploadEnvelopeData {
    return CommercialImportPreparedUploadEnvelopeDataToJSONTyped(json, false);
}

export function CommercialImportPreparedUploadEnvelopeDataToJSONTyped(value?: CommercialImportPreparedUploadEnvelopeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storage_key': value['storageKey'],
        'upload_url': value['uploadUrl'],
        'upload_headers': CommercialImportPreparedUploadEnvelopeDataUploadHeadersToJSON(value['uploadHeaders']),
        'expires_in_seconds': value['expiresInSeconds'],
    };
}

