/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommercialImportPreparedUploadEnvelopeDataUploadHeaders
 */
export interface CommercialImportPreparedUploadEnvelopeDataUploadHeaders {
    /**
     * 
     * @type {string}
     * @memberof CommercialImportPreparedUploadEnvelopeDataUploadHeaders
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof CommercialImportPreparedUploadEnvelopeDataUploadHeaders
     */
    xAmzChecksumSha256: string;
}

/**
 * Check if a given object implements the CommercialImportPreparedUploadEnvelopeDataUploadHeaders interface.
 */
export function instanceOfCommercialImportPreparedUploadEnvelopeDataUploadHeaders(value: object): value is CommercialImportPreparedUploadEnvelopeDataUploadHeaders {
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('xAmzChecksumSha256' in value) || value['xAmzChecksumSha256'] === undefined) return false;
    return true;
}

export function CommercialImportPreparedUploadEnvelopeDataUploadHeadersFromJSON(json: any): CommercialImportPreparedUploadEnvelopeDataUploadHeaders {
    return CommercialImportPreparedUploadEnvelopeDataUploadHeadersFromJSONTyped(json, false);
}

export function CommercialImportPreparedUploadEnvelopeDataUploadHeadersFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialImportPreparedUploadEnvelopeDataUploadHeaders {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': json['Content-Type'],
        'xAmzChecksumSha256': json['x-amz-checksum-sha256'],
    };
}

export function CommercialImportPreparedUploadEnvelopeDataUploadHeadersToJSON(json: any): CommercialImportPreparedUploadEnvelopeDataUploadHeaders {
    return CommercialImportPreparedUploadEnvelopeDataUploadHeadersToJSONTyped(json, false);
}

export function CommercialImportPreparedUploadEnvelopeDataUploadHeadersToJSONTyped(value?: CommercialImportPreparedUploadEnvelopeDataUploadHeaders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Content-Type': value['contentType'],
        'x-amz-checksum-sha256': value['xAmzChecksumSha256'],
    };
}

