/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateWebhookEndpointRequestSubscriptionsInner } from './CreateWebhookEndpointRequestSubscriptionsInner';
import {
    CreateWebhookEndpointRequestSubscriptionsInnerFromJSON,
    CreateWebhookEndpointRequestSubscriptionsInnerFromJSONTyped,
    CreateWebhookEndpointRequestSubscriptionsInnerToJSON,
    CreateWebhookEndpointRequestSubscriptionsInnerToJSONTyped,
} from './CreateWebhookEndpointRequestSubscriptionsInner';

/**
 * 
 * @export
 * @interface CreateWebhookEndpointRequest
 */
export interface CreateWebhookEndpointRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookEndpointRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookEndpointRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookEndpointRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Array<CreateWebhookEndpointRequestSubscriptionsInner>}
     * @memberof CreateWebhookEndpointRequest
     */
    subscriptions: Array<CreateWebhookEndpointRequestSubscriptionsInner>;
}

/**
 * Check if a given object implements the CreateWebhookEndpointRequest interface.
 */
export function instanceOfCreateWebhookEndpointRequest(value: object): value is CreateWebhookEndpointRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('subscriptions' in value) || value['subscriptions'] === undefined) return false;
    return true;
}

export function CreateWebhookEndpointRequestFromJSON(json: any): CreateWebhookEndpointRequest {
    return CreateWebhookEndpointRequestFromJSONTyped(json, false);
}

export function CreateWebhookEndpointRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookEndpointRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'description': json['description'] == null ? undefined : json['description'],
        'subscriptions': ((json['subscriptions'] as Array<any>).map(CreateWebhookEndpointRequestSubscriptionsInnerFromJSON)),
    };
}

export function CreateWebhookEndpointRequestToJSON(json: any): CreateWebhookEndpointRequest {
    return CreateWebhookEndpointRequestToJSONTyped(json, false);
}

export function CreateWebhookEndpointRequestToJSONTyped(value?: CreateWebhookEndpointRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'description': value['description'],
        'subscriptions': ((value['subscriptions'] as Array<any>).map(CreateWebhookEndpointRequestSubscriptionsInnerToJSON)),
    };
}

