/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAlertRuleRequest
 */
export interface CreateAlertRuleRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateAlertRuleRequest
     */
    condition: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAlertRuleRequest
     */
    productId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAlertRuleRequest
     */
    productName?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateAlertRuleRequest
     */
    storeIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateAlertRuleRequest
     */
    brandIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateAlertRuleRequest
     */
    categoryIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateAlertRuleRequest
     */
    thresholdPrice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateAlertRuleRequest
     */
    thresholdPercent?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAlertRuleRequest
     */
    notifyEmail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAlertRuleRequest
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the CreateAlertRuleRequest interface.
 */
export function instanceOfCreateAlertRuleRequest(value: object): value is CreateAlertRuleRequest {
    if (!('condition' in value) || value['condition'] === undefined) return false;
    return true;
}

export function CreateAlertRuleRequestFromJSON(json: any): CreateAlertRuleRequest {
    return CreateAlertRuleRequestFromJSONTyped(json, false);
}

export function CreateAlertRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAlertRuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'condition': json['condition'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'productName': json['productName'] == null ? undefined : json['productName'],
        'storeIds': json['storeIds'] == null ? undefined : json['storeIds'],
        'brandIds': json['brandIds'] == null ? undefined : json['brandIds'],
        'categoryIds': json['categoryIds'] == null ? undefined : json['categoryIds'],
        'thresholdPrice': json['thresholdPrice'] == null ? undefined : json['thresholdPrice'],
        'thresholdPercent': json['thresholdPercent'] == null ? undefined : json['thresholdPercent'],
        'notifyEmail': json['notifyEmail'] == null ? undefined : json['notifyEmail'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function CreateAlertRuleRequestToJSON(json: any): CreateAlertRuleRequest {
    return CreateAlertRuleRequestToJSONTyped(json, false);
}

export function CreateAlertRuleRequestToJSONTyped(value?: CreateAlertRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'condition': value['condition'],
        'productId': value['productId'],
        'productName': value['productName'],
        'storeIds': value['storeIds'],
        'brandIds': value['brandIds'],
        'categoryIds': value['categoryIds'],
        'thresholdPrice': value['thresholdPrice'],
        'thresholdPercent': value['thresholdPercent'],
        'notifyEmail': value['notifyEmail'],
        'isActive': value['isActive'],
    };
}

