/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommercialProductRequest
 */
export interface CreateCommercialProductRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialProductRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialProductRequest
     */
    parentProductId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialProductRequest
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialProductRequest
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialProductRequest
     */
    internalSku?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialProductRequest
     */
    externalSku?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialProductRequest
     */
    barcode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCommercialProductRequest
     */
    stockQuantity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCommercialProductRequest
     */
    stockThreshold?: number | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateCommercialProductRequest
     */
    attributes?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateCommercialProductRequest interface.
 */
export function instanceOfCreateCommercialProductRequest(value: object): value is CreateCommercialProductRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateCommercialProductRequestFromJSON(json: any): CreateCommercialProductRequest {
    return CreateCommercialProductRequestFromJSONTyped(json, false);
}

export function CreateCommercialProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommercialProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'parentProductId': json['parentProductId'] == null ? undefined : json['parentProductId'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'category': json['category'] == null ? undefined : json['category'],
        'internalSku': json['internalSku'] == null ? undefined : json['internalSku'],
        'externalSku': json['externalSku'] == null ? undefined : json['externalSku'],
        'barcode': json['barcode'] == null ? undefined : json['barcode'],
        'stockQuantity': json['stockQuantity'] == null ? undefined : json['stockQuantity'],
        'stockThreshold': json['stockThreshold'] == null ? undefined : json['stockThreshold'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
    };
}

export function CreateCommercialProductRequestToJSON(json: any): CreateCommercialProductRequest {
    return CreateCommercialProductRequestToJSONTyped(json, false);
}

export function CreateCommercialProductRequestToJSONTyped(value?: CreateCommercialProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'parentProductId': value['parentProductId'],
        'brand': value['brand'],
        'category': value['category'],
        'internalSku': value['internalSku'],
        'externalSku': value['externalSku'],
        'barcode': value['barcode'],
        'stockQuantity': value['stockQuantity'],
        'stockThreshold': value['stockThreshold'],
        'attributes': value['attributes'],
    };
}

