/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReportRequest
 */
export interface CreateReportRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateReportRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReportRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReportRequest
     */
    locale?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateReportRequest
     */
    schedule?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof CreateReportRequest
     */
    isActive?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateReportRequest
     */
    _configuration?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof CreateReportRequest
     */
    timezone?: string;
}

/**
 * Check if a given object implements the CreateReportRequest interface.
 */
export function instanceOfCreateReportRequest(value: object): value is CreateReportRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateReportRequestFromJSON(json: any): CreateReportRequest {
    return CreateReportRequestFromJSONTyped(json, false);
}

export function CreateReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        '_configuration': json['configuration'] == null ? undefined : json['configuration'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function CreateReportRequestToJSON(json: any): CreateReportRequest {
    return CreateReportRequestToJSONTyped(json, false);
}

export function CreateReportRequestToJSONTyped(value?: CreateReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'locale': value['locale'],
        'schedule': value['schedule'],
        'isActive': value['isActive'],
        'configuration': value['_configuration'],
        'timezone': value['timezone'],
    };
}

