/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommercialPartnerRequest
 */
export interface CreateCommercialPartnerRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialPartnerRequest
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateCommercialPartnerRequest
     */
    roles: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialPartnerRequest
     */
    contactName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialPartnerRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialPartnerRequest
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialPartnerRequest
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialPartnerRequest
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the CreateCommercialPartnerRequest interface.
 */
export function instanceOfCreateCommercialPartnerRequest(value: object): value is CreateCommercialPartnerRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    return true;
}

export function CreateCommercialPartnerRequestFromJSON(json: any): CreateCommercialPartnerRequest {
    return CreateCommercialPartnerRequestFromJSONTyped(json, false);
}

export function CreateCommercialPartnerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommercialPartnerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'roles': json['roles'],
        'contactName': json['contactName'] == null ? undefined : json['contactName'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'website': json['website'] == null ? undefined : json['website'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function CreateCommercialPartnerRequestToJSON(json: any): CreateCommercialPartnerRequest {
    return CreateCommercialPartnerRequestToJSONTyped(json, false);
}

export function CreateCommercialPartnerRequestToJSONTyped(value?: CreateCommercialPartnerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'roles': value['roles'],
        'contactName': value['contactName'],
        'email': value['email'],
        'phone': value['phone'],
        'website': value['website'],
        'notes': value['notes'],
    };
}

