/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateExportRequest
 */
export interface CreateExportRequest {
    /**
     * Lossless machine profile: ZIP with integration.csv (record_json column) and metadata.json. Exact decimal strings, stable IDs, UTC timestamps and publication provenance.
     * @type {CreateExportRequestProfileEnum}
     * @memberof CreateExportRequest
     */
    profile?: CreateExportRequestProfileEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateExportRequest
     */
    dataset: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExportRequest
     */
    format: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExportRequest
     */
    locale: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExportRequest
     */
    timezone: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateExportRequest
     */
    columns: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateExportRequest
     */
    filters?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof CreateExportRequest
     */
    name?: string;
}


/**
 * @export
 */
export const CreateExportRequestProfileEnum = {
    IntegrationV1: 'integration_v1'
} as const;
export type CreateExportRequestProfileEnum = typeof CreateExportRequestProfileEnum[keyof typeof CreateExportRequestProfileEnum];


/**
 * Check if a given object implements the CreateExportRequest interface.
 */
export function instanceOfCreateExportRequest(value: object): value is CreateExportRequest {
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('locale' in value) || value['locale'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('columns' in value) || value['columns'] === undefined) return false;
    return true;
}

export function CreateExportRequestFromJSON(json: any): CreateExportRequest {
    return CreateExportRequestFromJSONTyped(json, false);
}

export function CreateExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': json['profile'] == null ? undefined : json['profile'],
        'dataset': json['dataset'],
        'format': json['format'],
        'locale': json['locale'],
        'timezone': json['timezone'],
        'columns': json['columns'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CreateExportRequestToJSON(json: any): CreateExportRequest {
    return CreateExportRequestToJSONTyped(json, false);
}

export function CreateExportRequestToJSONTyped(value?: CreateExportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': value['profile'],
        'dataset': value['dataset'],
        'format': value['format'],
        'locale': value['locale'],
        'timezone': value['timezone'],
        'columns': value['columns'],
        'filters': value['filters'],
        'name': value['name'],
    };
}

