/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommercialImportRequest
 */
export interface CreateCommercialImportRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialImportRequest
     */
    kind: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialImportRequest
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialImportRequest
     */
    storageKey: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialImportRequest
     */
    contentSha256: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCommercialImportRequest
     */
    sizeBytes: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCommercialImportRequest
     */
    sheetName?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateCommercialImportRequest
     */
    mapping?: { [key: string]: any; };
    /**
     * 
     * @type {CreateCommercialImportRequestAutoMatchEnabledEnum}
     * @memberof CreateCommercialImportRequest
     */
    autoMatchEnabled?: CreateCommercialImportRequestAutoMatchEnabledEnum;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCommercialImportRequest
     */
    dryRun?: boolean;
}


/**
 * @export
 */
export const CreateCommercialImportRequestAutoMatchEnabledEnum = {
    False: false
} as const;
export type CreateCommercialImportRequestAutoMatchEnabledEnum = typeof CreateCommercialImportRequestAutoMatchEnabledEnum[keyof typeof CreateCommercialImportRequestAutoMatchEnabledEnum];


/**
 * Check if a given object implements the CreateCommercialImportRequest interface.
 */
export function instanceOfCreateCommercialImportRequest(value: object): value is CreateCommercialImportRequest {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('storageKey' in value) || value['storageKey'] === undefined) return false;
    if (!('contentSha256' in value) || value['contentSha256'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    return true;
}

export function CreateCommercialImportRequestFromJSON(json: any): CreateCommercialImportRequest {
    return CreateCommercialImportRequestFromJSONTyped(json, false);
}

export function CreateCommercialImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommercialImportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'fileName': json['fileName'],
        'storageKey': json['storageKey'],
        'contentSha256': json['contentSha256'],
        'sizeBytes': json['sizeBytes'],
        'sheetName': json['sheetName'] == null ? undefined : json['sheetName'],
        'mapping': json['mapping'] == null ? undefined : json['mapping'],
        'autoMatchEnabled': json['autoMatchEnabled'] == null ? undefined : json['autoMatchEnabled'],
        'dryRun': json['dryRun'] == null ? undefined : json['dryRun'],
    };
}

export function CreateCommercialImportRequestToJSON(json: any): CreateCommercialImportRequest {
    return CreateCommercialImportRequestToJSONTyped(json, false);
}

export function CreateCommercialImportRequestToJSONTyped(value?: CreateCommercialImportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'fileName': value['fileName'],
        'storageKey': value['storageKey'],
        'contentSha256': value['contentSha256'],
        'sizeBytes': value['sizeBytes'],
        'sheetName': value['sheetName'],
        'mapping': value['mapping'],
        'autoMatchEnabled': value['autoMatchEnabled'],
        'dryRun': value['dryRun'],
    };
}

