/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRepricerPolicyRequest
 */
export interface CreateRepricerPolicyRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRepricerPolicyRequest
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateRepricerPolicyRequest
     */
    enabled: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateRepricerPolicyRequest
     */
    priority: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateRepricerPolicyRequest
     */
    scope: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateRepricerPolicyRequest
     */
    config: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateRepricerPolicyRequest
     */
    guardrails: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateRepricerPolicyRequest interface.
 */
export function instanceOfCreateRepricerPolicyRequest(value: object): value is CreateRepricerPolicyRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('guardrails' in value) || value['guardrails'] === undefined) return false;
    return true;
}

export function CreateRepricerPolicyRequestFromJSON(json: any): CreateRepricerPolicyRequest {
    return CreateRepricerPolicyRequestFromJSONTyped(json, false);
}

export function CreateRepricerPolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRepricerPolicyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'enabled': json['enabled'],
        'priority': json['priority'],
        'scope': json['scope'],
        'config': json['config'],
        'guardrails': json['guardrails'],
    };
}

export function CreateRepricerPolicyRequestToJSON(json: any): CreateRepricerPolicyRequest {
    return CreateRepricerPolicyRequestToJSONTyped(json, false);
}

export function CreateRepricerPolicyRequestToJSONTyped(value?: CreateRepricerPolicyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'enabled': value['enabled'],
        'priority': value['priority'],
        'scope': value['scope'],
        'config': value['config'],
        'guardrails': value['guardrails'],
    };
}

