/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebhookEndpointRequestSubscriptionsInner
 */
export interface CreateWebhookEndpointRequestSubscriptionsInner {
    /**
     * 
     * @type {CreateWebhookEndpointRequestSubscriptionsInnerEventTypeEnum}
     * @memberof CreateWebhookEndpointRequestSubscriptionsInner
     */
    eventType: CreateWebhookEndpointRequestSubscriptionsInnerEventTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookEndpointRequestSubscriptionsInner
     */
    storeId: string | null;
}


/**
 * @export
 */
export const CreateWebhookEndpointRequestSubscriptionsInnerEventTypeEnum = {
    CatalogPublicationCompletedV1: 'catalog.publication.completed.v1',
    AlertRuleCreatedV1: 'alert.rule.created.v1',
    AlertRuleUpdatedV1: 'alert.rule.updated.v1',
    AlertRuleDeletedV1: 'alert.rule.deleted.v1',
    AlertEventCreatedV1: 'alert.event.created.v1',
    CommercialProductCreatedV1: 'commercial.product.created.v1',
    CommercialProductUpdatedV1: 'commercial.product.updated.v1',
    CommercialProductDeletedV1: 'commercial.product.deleted.v1',
    CommercialPartnerCreatedV1: 'commercial.partner.created.v1',
    CommercialPartnerUpdatedV1: 'commercial.partner.updated.v1',
    CommercialPartnerDeletedV1: 'commercial.partner.deleted.v1',
    CommercialSupplierOfferCreatedV1: 'commercial.supplier_offer.created.v1',
    CommercialSupplierOfferUpdatedV1: 'commercial.supplier_offer.updated.v1',
    CommercialSupplierOfferDeletedV1: 'commercial.supplier_offer.deleted.v1',
    CommercialPriceBookCreatedV1: 'commercial.price_book.created.v1',
    CommercialPriceBookUpdatedV1: 'commercial.price_book.updated.v1',
    CommercialPriceBookDeletedV1: 'commercial.price_book.deleted.v1',
    CommercialMarketLinkCreatedV1: 'commercial.market_link.created.v1',
    CommercialMarketLinkUpdatedV1: 'commercial.market_link.updated.v1',
    CommercialMarketLinkDeletedV1: 'commercial.market_link.deleted.v1',
    CommercialImportCompletedV1: 'commercial.import.completed.v1',
    CommercialImportFailedV1: 'commercial.import.failed.v1',
    CommercialImportCancelledV1: 'commercial.import.cancelled.v1',
    RepricerSettingsUpdatedV1: 'repricer.settings.updated.v1',
    RepricerPolicyCreatedV1: 'repricer.policy.created.v1',
    RepricerPolicyUpdatedV1: 'repricer.policy.updated.v1',
    RepricerPolicyDeletedV1: 'repricer.policy.deleted.v1',
    RepricerExclusionCreatedV1: 'repricer.exclusion.created.v1',
    RepricerExclusionDeletedV1: 'repricer.exclusion.deleted.v1',
    RepricerRunCompletedV1: 'repricer.run.completed.v1',
    RepricerRunFailedV1: 'repricer.run.failed.v1',
    RepricerRunCancelledV1: 'repricer.run.cancelled.v1',
    RepricerRecommendationUpdatedV1: 'repricer.recommendation.updated.v1',
    RepricerApplicationCompletedV1: 'repricer.application.completed.v1',
    RepricerApplicationFailedV1: 'repricer.application.failed.v1',
    ReportCompletedV1: 'report.completed.v1',
    ReportFailedV1: 'report.failed.v1',
    ExportCompletedV1: 'export.completed.v1',
    ExportFailedV1: 'export.failed.v1',
    ExportCancelledV1: 'export.cancelled.v1',
    EndpointTestV1: 'endpoint.test.v1'
} as const;
export type CreateWebhookEndpointRequestSubscriptionsInnerEventTypeEnum = typeof CreateWebhookEndpointRequestSubscriptionsInnerEventTypeEnum[keyof typeof CreateWebhookEndpointRequestSubscriptionsInnerEventTypeEnum];


/**
 * Check if a given object implements the CreateWebhookEndpointRequestSubscriptionsInner interface.
 */
export function instanceOfCreateWebhookEndpointRequestSubscriptionsInner(value: object): value is CreateWebhookEndpointRequestSubscriptionsInner {
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('storeId' in value) || value['storeId'] === undefined) return false;
    return true;
}

export function CreateWebhookEndpointRequestSubscriptionsInnerFromJSON(json: any): CreateWebhookEndpointRequestSubscriptionsInner {
    return CreateWebhookEndpointRequestSubscriptionsInnerFromJSONTyped(json, false);
}

export function CreateWebhookEndpointRequestSubscriptionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookEndpointRequestSubscriptionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'eventType': json['eventType'],
        'storeId': json['storeId'],
    };
}

export function CreateWebhookEndpointRequestSubscriptionsInnerToJSON(json: any): CreateWebhookEndpointRequestSubscriptionsInner {
    return CreateWebhookEndpointRequestSubscriptionsInnerToJSONTyped(json, false);
}

export function CreateWebhookEndpointRequestSubscriptionsInnerToJSONTyped(value?: CreateWebhookEndpointRequestSubscriptionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventType': value['eventType'],
        'storeId': value['storeId'],
    };
}

