/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRepricerExclusionRequest
 */
export interface CreateRepricerExclusionRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateRepricerExclusionRequest
     */
    scope: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof CreateRepricerExclusionRequest
     */
    reason: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateRepricerExclusionRequest
     */
    enabled: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CreateRepricerExclusionRequest
     */
    expiresAt: Date | null;
}

/**
 * Check if a given object implements the CreateRepricerExclusionRequest interface.
 */
export function instanceOfCreateRepricerExclusionRequest(value: object): value is CreateRepricerExclusionRequest {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function CreateRepricerExclusionRequestFromJSON(json: any): CreateRepricerExclusionRequest {
    return CreateRepricerExclusionRequestFromJSONTyped(json, false);
}

export function CreateRepricerExclusionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRepricerExclusionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'],
        'reason': json['reason'],
        'enabled': json['enabled'],
        'expiresAt': (json['expiresAt'] == null ? null : new Date(json['expiresAt'])),
    };
}

export function CreateRepricerExclusionRequestToJSON(json: any): CreateRepricerExclusionRequest {
    return CreateRepricerExclusionRequestToJSONTyped(json, false);
}

export function CreateRepricerExclusionRequestToJSONTyped(value?: CreateRepricerExclusionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'reason': value['reason'],
        'enabled': value['enabled'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
    };
}

