/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataEnvelope
 */
export interface DataEnvelope {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DataEnvelope
     */
    data: { [key: string]: any; };
}

/**
 * Check if a given object implements the DataEnvelope interface.
 */
export function instanceOfDataEnvelope(value: object): value is DataEnvelope {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DataEnvelopeFromJSON(json: any): DataEnvelope {
    return DataEnvelopeFromJSONTyped(json, false);
}

export function DataEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function DataEnvelopeToJSON(json: any): DataEnvelope {
    return DataEnvelopeToJSONTyped(json, false);
}

export function DataEnvelopeToJSONTyped(value?: DataEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

