/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteCommercialProductRequest
 */
export interface DeleteCommercialProductRequest {
    /**
     * 
     * @type {DeleteCommercialProductRequestChildVariantActionEnum}
     * @memberof DeleteCommercialProductRequest
     */
    childVariantAction: DeleteCommercialProductRequestChildVariantActionEnum;
}


/**
 * @export
 */
export const DeleteCommercialProductRequestChildVariantActionEnum = {
    MakeStandalone: 'makeStandalone',
    DeleteChildren: 'deleteChildren'
} as const;
export type DeleteCommercialProductRequestChildVariantActionEnum = typeof DeleteCommercialProductRequestChildVariantActionEnum[keyof typeof DeleteCommercialProductRequestChildVariantActionEnum];


/**
 * Check if a given object implements the DeleteCommercialProductRequest interface.
 */
export function instanceOfDeleteCommercialProductRequest(value: object): value is DeleteCommercialProductRequest {
    if (!('childVariantAction' in value) || value['childVariantAction'] === undefined) return false;
    return true;
}

export function DeleteCommercialProductRequestFromJSON(json: any): DeleteCommercialProductRequest {
    return DeleteCommercialProductRequestFromJSONTyped(json, false);
}

export function DeleteCommercialProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteCommercialProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'childVariantAction': json['childVariantAction'],
    };
}

export function DeleteCommercialProductRequestToJSON(json: any): DeleteCommercialProductRequest {
    return DeleteCommercialProductRequestToJSONTyped(json, false);
}

export function DeleteCommercialProductRequestToJSONTyped(value?: DeleteCommercialProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'childVariantAction': value['childVariantAction'],
    };
}

