/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EstimateExportRequest
 */
export interface EstimateExportRequest {
    /**
     * 
     * @type {string}
     * @memberof EstimateExportRequest
     */
    dataset: string;
    /**
     * 
     * @type {string}
     * @memberof EstimateExportRequest
     */
    format: string;
    /**
     * 
     * @type {string}
     * @memberof EstimateExportRequest
     */
    locale: string;
    /**
     * 
     * @type {string}
     * @memberof EstimateExportRequest
     */
    timezone: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EstimateExportRequest
     */
    columns: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EstimateExportRequest
     */
    filters?: { [key: string]: any; };
}

/**
 * Check if a given object implements the EstimateExportRequest interface.
 */
export function instanceOfEstimateExportRequest(value: object): value is EstimateExportRequest {
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('locale' in value) || value['locale'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('columns' in value) || value['columns'] === undefined) return false;
    return true;
}

export function EstimateExportRequestFromJSON(json: any): EstimateExportRequest {
    return EstimateExportRequestFromJSONTyped(json, false);
}

export function EstimateExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EstimateExportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'dataset': json['dataset'],
        'format': json['format'],
        'locale': json['locale'],
        'timezone': json['timezone'],
        'columns': json['columns'],
        'filters': json['filters'] == null ? undefined : json['filters'],
    };
}

export function EstimateExportRequestToJSON(json: any): EstimateExportRequest {
    return EstimateExportRequestToJSONTyped(json, false);
}

export function EstimateExportRequestToJSONTyped(value?: EstimateExportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dataset': value['dataset'],
        'format': value['format'],
        'locale': value['locale'],
        'timezone': value['timezone'],
        'columns': value['columns'],
        'filters': value['filters'],
    };
}

