/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEnvelopePage } from './ListEnvelopePage';
import {
    ListEnvelopePageFromJSON,
    ListEnvelopePageFromJSONTyped,
    ListEnvelopePageToJSON,
    ListEnvelopePageToJSONTyped,
} from './ListEnvelopePage';

/**
 * 
 * @export
 * @interface ListEnvelope
 */
export interface ListEnvelope {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof ListEnvelope
     */
    data: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {ListEnvelopePage}
     * @memberof ListEnvelope
     */
    page: ListEnvelopePage;
}

/**
 * Check if a given object implements the ListEnvelope interface.
 */
export function instanceOfListEnvelope(value: object): value is ListEnvelope {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    return true;
}

export function ListEnvelopeFromJSON(json: any): ListEnvelope {
    return ListEnvelopeFromJSONTyped(json, false);
}

export function ListEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'page': ListEnvelopePageFromJSON(json['page']),
    };
}

export function ListEnvelopeToJSON(json: any): ListEnvelope {
    return ListEnvelopeToJSONTyped(json, false);
}

export function ListEnvelopeToJSONTyped(value?: ListEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'page': ListEnvelopePageToJSON(value['page']),
    };
}

