/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListEnvelopePage
 */
export interface ListEnvelopePage {
    /**
     * 
     * @type {number}
     * @memberof ListEnvelopePage
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ListEnvelopePage
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof ListEnvelopePage
     */
    total: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListEnvelopePage
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the ListEnvelopePage interface.
 */
export function instanceOfListEnvelopePage(value: object): value is ListEnvelopePage {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function ListEnvelopePageFromJSON(json: any): ListEnvelopePage {
    return ListEnvelopePageFromJSONTyped(json, false);
}

export function ListEnvelopePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEnvelopePage {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'total': json['total'],
        'hasMore': json['has_more'],
    };
}

export function ListEnvelopePageToJSON(json: any): ListEnvelopePage {
    return ListEnvelopePageToJSONTyped(json, false);
}

export function ListEnvelopePageToJSONTyped(value?: ListEnvelopePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'total': value['total'],
        'has_more': value['hasMore'],
    };
}

