/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrepareCommercialImportUploadRequest
 */
export interface PrepareCommercialImportUploadRequest {
    /**
     * 
     * @type {string}
     * @memberof PrepareCommercialImportUploadRequest
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof PrepareCommercialImportUploadRequest
     */
    contentSha256: string;
    /**
     * 
     * @type {number}
     * @memberof PrepareCommercialImportUploadRequest
     */
    sizeBytes: number;
}

/**
 * Check if a given object implements the PrepareCommercialImportUploadRequest interface.
 */
export function instanceOfPrepareCommercialImportUploadRequest(value: object): value is PrepareCommercialImportUploadRequest {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('contentSha256' in value) || value['contentSha256'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    return true;
}

export function PrepareCommercialImportUploadRequestFromJSON(json: any): PrepareCommercialImportUploadRequest {
    return PrepareCommercialImportUploadRequestFromJSONTyped(json, false);
}

export function PrepareCommercialImportUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareCommercialImportUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'],
        'contentSha256': json['contentSha256'],
        'sizeBytes': json['sizeBytes'],
    };
}

export function PrepareCommercialImportUploadRequestToJSON(json: any): PrepareCommercialImportUploadRequest {
    return PrepareCommercialImportUploadRequestToJSONTyped(json, false);
}

export function PrepareCommercialImportUploadRequestToJSONTyped(value?: PrepareCommercialImportUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileName': value['fileName'],
        'contentSha256': value['contentSha256'],
        'sizeBytes': value['sizeBytes'],
    };
}

