/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiveRivalikaWebhookRequest
 */
export interface ReceiveRivalikaWebhookRequest {
    /**
     * 
     * @type {string}
     * @memberof ReceiveRivalikaWebhookRequest
     */
    id: string;
    /**
     * 
     * @type {ReceiveRivalikaWebhookRequestTypeEnum}
     * @memberof ReceiveRivalikaWebhookRequest
     */
    type: ReceiveRivalikaWebhookRequestTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof ReceiveRivalikaWebhookRequest
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ReceiveRivalikaWebhookRequest
     */
    organizationId: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ReceiveRivalikaWebhookRequest
     */
    data: { [key: string]: any; };
}


/**
 * @export
 */
export const ReceiveRivalikaWebhookRequestTypeEnum = {
    CatalogPublicationCompletedV1: 'catalog.publication.completed.v1',
    AlertRuleCreatedV1: 'alert.rule.created.v1',
    AlertRuleUpdatedV1: 'alert.rule.updated.v1',
    AlertRuleDeletedV1: 'alert.rule.deleted.v1',
    AlertEventCreatedV1: 'alert.event.created.v1',
    CommercialProductCreatedV1: 'commercial.product.created.v1',
    CommercialProductUpdatedV1: 'commercial.product.updated.v1',
    CommercialProductDeletedV1: 'commercial.product.deleted.v1',
    CommercialPartnerCreatedV1: 'commercial.partner.created.v1',
    CommercialPartnerUpdatedV1: 'commercial.partner.updated.v1',
    CommercialPartnerDeletedV1: 'commercial.partner.deleted.v1',
    CommercialSupplierOfferCreatedV1: 'commercial.supplier_offer.created.v1',
    CommercialSupplierOfferUpdatedV1: 'commercial.supplier_offer.updated.v1',
    CommercialSupplierOfferDeletedV1: 'commercial.supplier_offer.deleted.v1',
    CommercialPriceBookCreatedV1: 'commercial.price_book.created.v1',
    CommercialPriceBookUpdatedV1: 'commercial.price_book.updated.v1',
    CommercialPriceBookDeletedV1: 'commercial.price_book.deleted.v1',
    CommercialMarketLinkCreatedV1: 'commercial.market_link.created.v1',
    CommercialMarketLinkUpdatedV1: 'commercial.market_link.updated.v1',
    CommercialMarketLinkDeletedV1: 'commercial.market_link.deleted.v1',
    CommercialImportCompletedV1: 'commercial.import.completed.v1',
    CommercialImportFailedV1: 'commercial.import.failed.v1',
    CommercialImportCancelledV1: 'commercial.import.cancelled.v1',
    RepricerSettingsUpdatedV1: 'repricer.settings.updated.v1',
    RepricerPolicyCreatedV1: 'repricer.policy.created.v1',
    RepricerPolicyUpdatedV1: 'repricer.policy.updated.v1',
    RepricerPolicyDeletedV1: 'repricer.policy.deleted.v1',
    RepricerExclusionCreatedV1: 'repricer.exclusion.created.v1',
    RepricerExclusionDeletedV1: 'repricer.exclusion.deleted.v1',
    RepricerRunCompletedV1: 'repricer.run.completed.v1',
    RepricerRunFailedV1: 'repricer.run.failed.v1',
    RepricerRunCancelledV1: 'repricer.run.cancelled.v1',
    RepricerRecommendationUpdatedV1: 'repricer.recommendation.updated.v1',
    RepricerApplicationCompletedV1: 'repricer.application.completed.v1',
    RepricerApplicationFailedV1: 'repricer.application.failed.v1',
    ReportCompletedV1: 'report.completed.v1',
    ReportFailedV1: 'report.failed.v1',
    ExportCompletedV1: 'export.completed.v1',
    ExportFailedV1: 'export.failed.v1',
    ExportCancelledV1: 'export.cancelled.v1',
    EndpointTestV1: 'endpoint.test.v1'
} as const;
export type ReceiveRivalikaWebhookRequestTypeEnum = typeof ReceiveRivalikaWebhookRequestTypeEnum[keyof typeof ReceiveRivalikaWebhookRequestTypeEnum];


/**
 * Check if a given object implements the ReceiveRivalikaWebhookRequest interface.
 */
export function instanceOfReceiveRivalikaWebhookRequest(value: object): value is ReceiveRivalikaWebhookRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ReceiveRivalikaWebhookRequestFromJSON(json: any): ReceiveRivalikaWebhookRequest {
    return ReceiveRivalikaWebhookRequestFromJSONTyped(json, false);
}

export function ReceiveRivalikaWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiveRivalikaWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'createdAt': (new Date(json['created_at'])),
        'organizationId': json['organization_id'],
        'data': json['data'],
    };
}

export function ReceiveRivalikaWebhookRequestToJSON(json: any): ReceiveRivalikaWebhookRequest {
    return ReceiveRivalikaWebhookRequestToJSONTyped(json, false);
}

export function ReceiveRivalikaWebhookRequestToJSONTyped(value?: ReceiveRivalikaWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'created_at': value['createdAt'].toISOString(),
        'organization_id': value['organizationId'],
        'data': value['data'],
    };
}

