/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetAlertRuleRecipientsRequestRecipientsInner
 */
export interface SetAlertRuleRecipientsRequestRecipientsInner {
    /**
     * 
     * @type {string}
     * @memberof SetAlertRuleRecipientsRequestRecipientsInner
     */
    userId: string;
    /**
     * 
     * @type {boolean}
     * @memberof SetAlertRuleRecipientsRequestRecipientsInner
     */
    notifyEmail: boolean;
}

/**
 * Check if a given object implements the SetAlertRuleRecipientsRequestRecipientsInner interface.
 */
export function instanceOfSetAlertRuleRecipientsRequestRecipientsInner(value: object): value is SetAlertRuleRecipientsRequestRecipientsInner {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('notifyEmail' in value) || value['notifyEmail'] === undefined) return false;
    return true;
}

export function SetAlertRuleRecipientsRequestRecipientsInnerFromJSON(json: any): SetAlertRuleRecipientsRequestRecipientsInner {
    return SetAlertRuleRecipientsRequestRecipientsInnerFromJSONTyped(json, false);
}

export function SetAlertRuleRecipientsRequestRecipientsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetAlertRuleRecipientsRequestRecipientsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'notifyEmail': json['notifyEmail'],
    };
}

export function SetAlertRuleRecipientsRequestRecipientsInnerToJSON(json: any): SetAlertRuleRecipientsRequestRecipientsInner {
    return SetAlertRuleRecipientsRequestRecipientsInnerToJSONTyped(json, false);
}

export function SetAlertRuleRecipientsRequestRecipientsInnerToJSONTyped(value?: SetAlertRuleRecipientsRequestRecipientsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'notifyEmail': value['notifyEmail'],
    };
}

