/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetAlertRuleRecipientsRequestRecipientsInner } from './SetAlertRuleRecipientsRequestRecipientsInner';
import {
    SetAlertRuleRecipientsRequestRecipientsInnerFromJSON,
    SetAlertRuleRecipientsRequestRecipientsInnerFromJSONTyped,
    SetAlertRuleRecipientsRequestRecipientsInnerToJSON,
    SetAlertRuleRecipientsRequestRecipientsInnerToJSONTyped,
} from './SetAlertRuleRecipientsRequestRecipientsInner';

/**
 * 
 * @export
 * @interface SetAlertRuleRecipientsRequest
 */
export interface SetAlertRuleRecipientsRequest {
    /**
     * 
     * @type {Array<SetAlertRuleRecipientsRequestRecipientsInner>}
     * @memberof SetAlertRuleRecipientsRequest
     */
    recipients: Array<SetAlertRuleRecipientsRequestRecipientsInner>;
}

/**
 * Check if a given object implements the SetAlertRuleRecipientsRequest interface.
 */
export function instanceOfSetAlertRuleRecipientsRequest(value: object): value is SetAlertRuleRecipientsRequest {
    if (!('recipients' in value) || value['recipients'] === undefined) return false;
    return true;
}

export function SetAlertRuleRecipientsRequestFromJSON(json: any): SetAlertRuleRecipientsRequest {
    return SetAlertRuleRecipientsRequestFromJSONTyped(json, false);
}

export function SetAlertRuleRecipientsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetAlertRuleRecipientsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipients': ((json['recipients'] as Array<any>).map(SetAlertRuleRecipientsRequestRecipientsInnerFromJSON)),
    };
}

export function SetAlertRuleRecipientsRequestToJSON(json: any): SetAlertRuleRecipientsRequest {
    return SetAlertRuleRecipientsRequestToJSONTyped(json, false);
}

export function SetAlertRuleRecipientsRequestToJSONTyped(value?: SetAlertRuleRecipientsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipients': ((value['recipients'] as Array<any>).map(SetAlertRuleRecipientsRequestRecipientsInnerToJSON)),
    };
}

