/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAlertRuleRequest
 */
export interface UpdateAlertRuleRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertRuleRequest
     */
    productId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertRuleRequest
     */
    productName?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAlertRuleRequest
     */
    storeIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAlertRuleRequest
     */
    brandIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAlertRuleRequest
     */
    categoryIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertRuleRequest
     */
    condition?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateAlertRuleRequest
     */
    thresholdPrice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateAlertRuleRequest
     */
    thresholdPercent?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertRuleRequest
     */
    cooldown?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAlertRuleRequest
     */
    notifyEmail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAlertRuleRequest
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the UpdateAlertRuleRequest interface.
 */
export function instanceOfUpdateAlertRuleRequest(value: object): value is UpdateAlertRuleRequest {
    return true;
}

export function UpdateAlertRuleRequestFromJSON(json: any): UpdateAlertRuleRequest {
    return UpdateAlertRuleRequestFromJSONTyped(json, false);
}

export function UpdateAlertRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAlertRuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'] == null ? undefined : json['productId'],
        'productName': json['productName'] == null ? undefined : json['productName'],
        'storeIds': json['storeIds'] == null ? undefined : json['storeIds'],
        'brandIds': json['brandIds'] == null ? undefined : json['brandIds'],
        'categoryIds': json['categoryIds'] == null ? undefined : json['categoryIds'],
        'condition': json['condition'] == null ? undefined : json['condition'],
        'thresholdPrice': json['thresholdPrice'] == null ? undefined : json['thresholdPrice'],
        'thresholdPercent': json['thresholdPercent'] == null ? undefined : json['thresholdPercent'],
        'cooldown': json['cooldown'] == null ? undefined : json['cooldown'],
        'notifyEmail': json['notifyEmail'] == null ? undefined : json['notifyEmail'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function UpdateAlertRuleRequestToJSON(json: any): UpdateAlertRuleRequest {
    return UpdateAlertRuleRequestToJSONTyped(json, false);
}

export function UpdateAlertRuleRequestToJSONTyped(value?: UpdateAlertRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'productName': value['productName'],
        'storeIds': value['storeIds'],
        'brandIds': value['brandIds'],
        'categoryIds': value['categoryIds'],
        'condition': value['condition'],
        'thresholdPrice': value['thresholdPrice'],
        'thresholdPercent': value['thresholdPercent'],
        'cooldown': value['cooldown'],
        'notifyEmail': value['notifyEmail'],
        'isActive': value['isActive'],
    };
}

