/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCommercialPartnerRequest
 */
export interface UpdateCommercialPartnerRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCommercialPartnerRequest
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateCommercialPartnerRequest
     */
    roles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommercialPartnerRequest
     */
    contactName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommercialPartnerRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommercialPartnerRequest
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommercialPartnerRequest
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommercialPartnerRequest
     */
    notes?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCommercialPartnerRequest
     */
    active?: boolean;
}

/**
 * Check if a given object implements the UpdateCommercialPartnerRequest interface.
 */
export function instanceOfUpdateCommercialPartnerRequest(value: object): value is UpdateCommercialPartnerRequest {
    return true;
}

export function UpdateCommercialPartnerRequestFromJSON(json: any): UpdateCommercialPartnerRequest {
    return UpdateCommercialPartnerRequestFromJSONTyped(json, false);
}

export function UpdateCommercialPartnerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCommercialPartnerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'contactName': json['contactName'] == null ? undefined : json['contactName'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'website': json['website'] == null ? undefined : json['website'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function UpdateCommercialPartnerRequestToJSON(json: any): UpdateCommercialPartnerRequest {
    return UpdateCommercialPartnerRequestToJSONTyped(json, false);
}

export function UpdateCommercialPartnerRequestToJSONTyped(value?: UpdateCommercialPartnerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'roles': value['roles'],
        'contactName': value['contactName'],
        'email': value['email'],
        'phone': value['phone'],
        'website': value['website'],
        'notes': value['notes'],
        'active': value['active'],
    };
}

