/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAlertSettingsRequest
 */
export interface UpdateAlertSettingsRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAlertSettingsRequest
     */
    defaultNotifyEmail?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertSettingsRequest
     */
    quietHoursStartUtc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertSettingsRequest
     */
    quietHoursEndUtc?: string | null;
}

/**
 * Check if a given object implements the UpdateAlertSettingsRequest interface.
 */
export function instanceOfUpdateAlertSettingsRequest(value: object): value is UpdateAlertSettingsRequest {
    return true;
}

export function UpdateAlertSettingsRequestFromJSON(json: any): UpdateAlertSettingsRequest {
    return UpdateAlertSettingsRequestFromJSONTyped(json, false);
}

export function UpdateAlertSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAlertSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultNotifyEmail': json['defaultNotifyEmail'] == null ? undefined : json['defaultNotifyEmail'],
        'quietHoursStartUtc': json['quietHoursStartUtc'] == null ? undefined : json['quietHoursStartUtc'],
        'quietHoursEndUtc': json['quietHoursEndUtc'] == null ? undefined : json['quietHoursEndUtc'],
    };
}

export function UpdateAlertSettingsRequestToJSON(json: any): UpdateAlertSettingsRequest {
    return UpdateAlertSettingsRequestToJSONTyped(json, false);
}

export function UpdateAlertSettingsRequestToJSONTyped(value?: UpdateAlertSettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'defaultNotifyEmail': value['defaultNotifyEmail'],
        'quietHoursStartUtc': value['quietHoursStartUtc'],
        'quietHoursEndUtc': value['quietHoursEndUtc'],
    };
}

