/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRepricerSettingsRequest
 */
export interface UpdateRepricerSettingsRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateRepricerSettingsRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateRepricerSettingsRequest
     */
    timezone?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateRepricerSettingsRequest
     */
    schedule?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof UpdateRepricerSettingsRequest
     */
    recommendationLifetimeHours?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateRepricerSettingsRequest
     */
    evidenceMaxAgeHours?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateRepricerSettingsRequest
     */
    minimumInStockObservations?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateRepricerSettingsRequest
     */
    maximumMovePercent?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateRepricerSettingsRequest
     */
    batchApplyLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateRepricerSettingsRequest
     */
    evidenceCap?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateRepricerSettingsRequest
     */
    roundingMode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRepricerSettingsRequest
     */
    priceEnding?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateRepricerSettingsRequest
     */
    lowStockProtectionEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdateRepricerSettingsRequest
     */
    lowStockThreshold?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateRepricerSettingsRequest
     */
    b2bTierMode?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateRepricerSettingsRequest
     */
    excludedStoreIds?: Array<string>;
}

/**
 * Check if a given object implements the UpdateRepricerSettingsRequest interface.
 */
export function instanceOfUpdateRepricerSettingsRequest(value: object): value is UpdateRepricerSettingsRequest {
    return true;
}

export function UpdateRepricerSettingsRequestFromJSON(json: any): UpdateRepricerSettingsRequest {
    return UpdateRepricerSettingsRequestFromJSONTyped(json, false);
}

export function UpdateRepricerSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRepricerSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        'recommendationLifetimeHours': json['recommendationLifetimeHours'] == null ? undefined : json['recommendationLifetimeHours'],
        'evidenceMaxAgeHours': json['evidenceMaxAgeHours'] == null ? undefined : json['evidenceMaxAgeHours'],
        'minimumInStockObservations': json['minimumInStockObservations'] == null ? undefined : json['minimumInStockObservations'],
        'maximumMovePercent': json['maximumMovePercent'] == null ? undefined : json['maximumMovePercent'],
        'batchApplyLimit': json['batchApplyLimit'] == null ? undefined : json['batchApplyLimit'],
        'evidenceCap': json['evidenceCap'] == null ? undefined : json['evidenceCap'],
        'roundingMode': json['roundingMode'] == null ? undefined : json['roundingMode'],
        'priceEnding': json['priceEnding'] == null ? undefined : json['priceEnding'],
        'lowStockProtectionEnabled': json['lowStockProtectionEnabled'] == null ? undefined : json['lowStockProtectionEnabled'],
        'lowStockThreshold': json['lowStockThreshold'] == null ? undefined : json['lowStockThreshold'],
        'b2bTierMode': json['b2bTierMode'] == null ? undefined : json['b2bTierMode'],
        'excludedStoreIds': json['excludedStoreIds'] == null ? undefined : json['excludedStoreIds'],
    };
}

export function UpdateRepricerSettingsRequestToJSON(json: any): UpdateRepricerSettingsRequest {
    return UpdateRepricerSettingsRequestToJSONTyped(json, false);
}

export function UpdateRepricerSettingsRequestToJSONTyped(value?: UpdateRepricerSettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'enabled': value['enabled'],
        'timezone': value['timezone'],
        'schedule': value['schedule'],
        'recommendationLifetimeHours': value['recommendationLifetimeHours'],
        'evidenceMaxAgeHours': value['evidenceMaxAgeHours'],
        'minimumInStockObservations': value['minimumInStockObservations'],
        'maximumMovePercent': value['maximumMovePercent'],
        'batchApplyLimit': value['batchApplyLimit'],
        'evidenceCap': value['evidenceCap'],
        'roundingMode': value['roundingMode'],
        'priceEnding': value['priceEnding'],
        'lowStockProtectionEnabled': value['lowStockProtectionEnabled'],
        'lowStockThreshold': value['lowStockThreshold'],
        'b2bTierMode': value['b2bTierMode'],
        'excludedStoreIds': value['excludedStoreIds'],
    };
}

