/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSupplierOfferRequest
 */
export interface UpdateSupplierOfferRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateSupplierOfferRequest
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSupplierOfferRequest
     */
    partnerId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSupplierOfferRequest
     */
    supplierSku?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateSupplierOfferRequest
     */
    costAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateSupplierOfferRequest
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateSupplierOfferRequest
     */
    minOrderQuantity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateSupplierOfferRequest
     */
    leadTimeDays?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateSupplierOfferRequest
     */
    validFrom?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateSupplierOfferRequest
     */
    validTo?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateSupplierOfferRequest
     */
    isPreferred?: boolean;
}

/**
 * Check if a given object implements the UpdateSupplierOfferRequest interface.
 */
export function instanceOfUpdateSupplierOfferRequest(value: object): value is UpdateSupplierOfferRequest {
    return true;
}

export function UpdateSupplierOfferRequestFromJSON(json: any): UpdateSupplierOfferRequest {
    return UpdateSupplierOfferRequestFromJSONTyped(json, false);
}

export function UpdateSupplierOfferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSupplierOfferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'] == null ? undefined : json['productId'],
        'partnerId': json['partnerId'] == null ? undefined : json['partnerId'],
        'supplierSku': json['supplierSku'] == null ? undefined : json['supplierSku'],
        'costAmount': json['costAmount'] == null ? undefined : json['costAmount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'minOrderQuantity': json['minOrderQuantity'] == null ? undefined : json['minOrderQuantity'],
        'leadTimeDays': json['leadTimeDays'] == null ? undefined : json['leadTimeDays'],
        'validFrom': json['validFrom'] == null ? undefined : (new Date(json['validFrom'])),
        'validTo': json['validTo'] == null ? undefined : (new Date(json['validTo'])),
        'isPreferred': json['isPreferred'] == null ? undefined : json['isPreferred'],
    };
}

export function UpdateSupplierOfferRequestToJSON(json: any): UpdateSupplierOfferRequest {
    return UpdateSupplierOfferRequestToJSONTyped(json, false);
}

export function UpdateSupplierOfferRequestToJSONTyped(value?: UpdateSupplierOfferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'partnerId': value['partnerId'],
        'supplierSku': value['supplierSku'],
        'costAmount': value['costAmount'],
        'currency': value['currency'],
        'minOrderQuantity': value['minOrderQuantity'],
        'leadTimeDays': value['leadTimeDays'],
        'validFrom': value['validFrom'] == null ? value['validFrom'] : value['validFrom'].toISOString().substring(0,10),
        'validTo': value['validTo'] == null ? value['validTo'] : value['validTo'].toISOString().substring(0,10),
        'isPreferred': value['isPreferred'],
    };
}

