/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePriceBookRequest
 */
export interface UpdatePriceBookRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePriceBookRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePriceBookRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePriceBookRequest
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePriceBookRequest
     */
    currency?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePriceBookRequest
     */
    isDefault?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePriceBookRequest
     */
    active?: boolean;
}

/**
 * Check if a given object implements the UpdatePriceBookRequest interface.
 */
export function instanceOfUpdatePriceBookRequest(value: object): value is UpdatePriceBookRequest {
    return true;
}

export function UpdatePriceBookRequestFromJSON(json: any): UpdatePriceBookRequest {
    return UpdatePriceBookRequestFromJSONTyped(json, false);
}

export function UpdatePriceBookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePriceBookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function UpdatePriceBookRequestToJSON(json: any): UpdatePriceBookRequest {
    return UpdatePriceBookRequestToJSONTyped(json, false);
}

export function UpdatePriceBookRequestToJSONTyped(value?: UpdatePriceBookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'kind': value['kind'],
        'currency': value['currency'],
        'isDefault': value['isDefault'],
        'active': value['active'],
    };
}

