/* tslint:disable */
/* eslint-disable */
/**
 * Rivalika Public API
 * Stable business integration API for Rivalika customers.
 *
 * The version of the OpenAPI document: 1.0.0-beta.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateReportRequest
 */
export interface UpdateReportRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateReportRequest
     */
    timezone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateReportRequest
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateReportRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateReportRequest
     */
    locale?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateReportRequest
     */
    schedule?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof UpdateReportRequest
     */
    isActive?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateReportRequest
     */
    _configuration?: { [key: string]: any; };
}

/**
 * Check if a given object implements the UpdateReportRequest interface.
 */
export function instanceOfUpdateReportRequest(value: object): value is UpdateReportRequest {
    return true;
}

export function UpdateReportRequestFromJSON(json: any): UpdateReportRequest {
    return UpdateReportRequestFromJSONTyped(json, false);
}

export function UpdateReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        '_configuration': json['configuration'] == null ? undefined : json['configuration'],
    };
}

export function UpdateReportRequestToJSON(json: any): UpdateReportRequest {
    return UpdateReportRequestToJSONTyped(json, false);
}

export function UpdateReportRequestToJSONTyped(value?: UpdateReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timezone': value['timezone'],
        'type': value['type'],
        'name': value['name'],
        'locale': value['locale'],
        'schedule': value['schedule'],
        'isActive': value['isActive'],
        'configuration': value['_configuration'],
    };
}

